/*
Manticore Search Client

Сlient for Manticore Search. 

API version: 5.0.0
Contact: info@manticoresearch.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the KnnSearchRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &KnnSearchRequest{}

// KnnSearchRequest Request object for knn search operation
type KnnSearchRequest struct {
	Aggs *Aggregation `json:"aggs,omitempty"`
	Expressions map[string]string `json:"expressions,omitempty"`
	Join []JoinInner `json:"join,omitempty"`
	Highlight *Highlight `json:"highlight,omitempty"`
	Index string `json:"index"`
	Limit *int32 `json:"limit,omitempty"`
	MaxMatches *int32 `json:"max_matches,omitempty"`
	Offset *int32 `json:"offset,omitempty"`
	Options map[string]interface{} `json:"options,omitempty"`
	Profile *bool `json:"profile,omitempty"`
	Sort []SearchRequestParametersSortInner `json:"sort,omitempty"`
	Source *SearchRequestParametersSource `json:"_source,omitempty"`
	TrackScores *bool `json:"track_scores,omitempty"`
	Knn KnnSearchRequestAllOfKnn `json:"knn"`
}

type _KnnSearchRequest KnnSearchRequest

// NewKnnSearchRequest instantiates a new KnnSearchRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKnnSearchRequest(index string, knn KnnSearchRequestAllOfKnn) *KnnSearchRequest {
	this := KnnSearchRequest{}
	this.Index = index
	this.Knn = knn
	return &this
}

// NewKnnSearchRequestWithDefaults instantiates a new KnnSearchRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKnnSearchRequestWithDefaults() *KnnSearchRequest {
	this := KnnSearchRequest{}
	return &this
}

// GetAggs returns the Aggs field value if set, zero value otherwise.
func (o *KnnSearchRequest) GetAggs() Aggregation {
	if o == nil || IsNil(o.Aggs) {
		var ret Aggregation
		return ret
	}
	return *o.Aggs
}

// GetAggsOk returns a tuple with the Aggs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KnnSearchRequest) GetAggsOk() (*Aggregation, bool) {
	if o == nil || IsNil(o.Aggs) {
		return nil, false
	}
	return o.Aggs, true
}

// HasAggs returns a boolean if a field has been set.
func (o *KnnSearchRequest) HasAggs() bool {
	if o != nil && !IsNil(o.Aggs) {
		return true
	}

	return false
}

// SetAggs gets a reference to the given Aggregation and assigns it to the Aggs field.
func (o *KnnSearchRequest) SetAggs(v Aggregation) {
	o.Aggs = &v
}

// GetExpressions returns the Expressions field value if set, zero value otherwise.
func (o *KnnSearchRequest) GetExpressions() map[string]string {
	if o == nil || IsNil(o.Expressions) {
		var ret map[string]string
		return ret
	}
	return o.Expressions
}

// GetExpressionsOk returns a tuple with the Expressions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KnnSearchRequest) GetExpressionsOk() (map[string]string, bool) {
	if o == nil || IsNil(o.Expressions) {
		return map[string]string{}, false
	}
	return o.Expressions, true
}

// HasExpressions returns a boolean if a field has been set.
func (o *KnnSearchRequest) HasExpressions() bool {
	if o != nil && !IsNil(o.Expressions) {
		return true
	}

	return false
}

// SetExpressions gets a reference to the given map[string]string and assigns it to the Expressions field.
func (o *KnnSearchRequest) SetExpressions(v map[string]string) {
	o.Expressions = v
}

// GetJoin returns the Join field value if set, zero value otherwise.
func (o *KnnSearchRequest) GetJoin() []JoinInner {
	if o == nil || IsNil(o.Join) {
		var ret []JoinInner
		return ret
	}
	return o.Join
}

// GetJoinOk returns a tuple with the Join field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KnnSearchRequest) GetJoinOk() ([]JoinInner, bool) {
	if o == nil || IsNil(o.Join) {
		return nil, false
	}
	return o.Join, true
}

// HasJoin returns a boolean if a field has been set.
func (o *KnnSearchRequest) HasJoin() bool {
	if o != nil && !IsNil(o.Join) {
		return true
	}

	return false
}

// SetJoin gets a reference to the given []JoinInner and assigns it to the Join field.
func (o *KnnSearchRequest) SetJoin(v []JoinInner) {
	o.Join = v
}

// GetHighlight returns the Highlight field value if set, zero value otherwise.
func (o *KnnSearchRequest) GetHighlight() Highlight {
	if o == nil || IsNil(o.Highlight) {
		var ret Highlight
		return ret
	}
	return *o.Highlight
}

// GetHighlightOk returns a tuple with the Highlight field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KnnSearchRequest) GetHighlightOk() (*Highlight, bool) {
	if o == nil || IsNil(o.Highlight) {
		return nil, false
	}
	return o.Highlight, true
}

// HasHighlight returns a boolean if a field has been set.
func (o *KnnSearchRequest) HasHighlight() bool {
	if o != nil && !IsNil(o.Highlight) {
		return true
	}

	return false
}

// SetHighlight gets a reference to the given Highlight and assigns it to the Highlight field.
func (o *KnnSearchRequest) SetHighlight(v Highlight) {
	o.Highlight = &v
}

// GetIndex returns the Index field value
func (o *KnnSearchRequest) GetIndex() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Index
}

// GetIndexOk returns a tuple with the Index field value
// and a boolean to check if the value has been set.
func (o *KnnSearchRequest) GetIndexOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Index, true
}

// SetIndex sets field value
func (o *KnnSearchRequest) SetIndex(v string) {
	o.Index = v
}

// GetLimit returns the Limit field value if set, zero value otherwise.
func (o *KnnSearchRequest) GetLimit() int32 {
	if o == nil || IsNil(o.Limit) {
		var ret int32
		return ret
	}
	return *o.Limit
}

// GetLimitOk returns a tuple with the Limit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KnnSearchRequest) GetLimitOk() (*int32, bool) {
	if o == nil || IsNil(o.Limit) {
		return nil, false
	}
	return o.Limit, true
}

// HasLimit returns a boolean if a field has been set.
func (o *KnnSearchRequest) HasLimit() bool {
	if o != nil && !IsNil(o.Limit) {
		return true
	}

	return false
}

// SetLimit gets a reference to the given int32 and assigns it to the Limit field.
func (o *KnnSearchRequest) SetLimit(v int32) {
	o.Limit = &v
}

// GetMaxMatches returns the MaxMatches field value if set, zero value otherwise.
func (o *KnnSearchRequest) GetMaxMatches() int32 {
	if o == nil || IsNil(o.MaxMatches) {
		var ret int32
		return ret
	}
	return *o.MaxMatches
}

// GetMaxMatchesOk returns a tuple with the MaxMatches field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KnnSearchRequest) GetMaxMatchesOk() (*int32, bool) {
	if o == nil || IsNil(o.MaxMatches) {
		return nil, false
	}
	return o.MaxMatches, true
}

// HasMaxMatches returns a boolean if a field has been set.
func (o *KnnSearchRequest) HasMaxMatches() bool {
	if o != nil && !IsNil(o.MaxMatches) {
		return true
	}

	return false
}

// SetMaxMatches gets a reference to the given int32 and assigns it to the MaxMatches field.
func (o *KnnSearchRequest) SetMaxMatches(v int32) {
	o.MaxMatches = &v
}

// GetOffset returns the Offset field value if set, zero value otherwise.
func (o *KnnSearchRequest) GetOffset() int32 {
	if o == nil || IsNil(o.Offset) {
		var ret int32
		return ret
	}
	return *o.Offset
}

// GetOffsetOk returns a tuple with the Offset field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KnnSearchRequest) GetOffsetOk() (*int32, bool) {
	if o == nil || IsNil(o.Offset) {
		return nil, false
	}
	return o.Offset, true
}

// HasOffset returns a boolean if a field has been set.
func (o *KnnSearchRequest) HasOffset() bool {
	if o != nil && !IsNil(o.Offset) {
		return true
	}

	return false
}

// SetOffset gets a reference to the given int32 and assigns it to the Offset field.
func (o *KnnSearchRequest) SetOffset(v int32) {
	o.Offset = &v
}

// GetOptions returns the Options field value if set, zero value otherwise.
func (o *KnnSearchRequest) GetOptions() map[string]interface{} {
	if o == nil || IsNil(o.Options) {
		var ret map[string]interface{}
		return ret
	}
	return o.Options
}

// GetOptionsOk returns a tuple with the Options field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KnnSearchRequest) GetOptionsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Options) {
		return map[string]interface{}{}, false
	}
	return o.Options, true
}

// HasOptions returns a boolean if a field has been set.
func (o *KnnSearchRequest) HasOptions() bool {
	if o != nil && !IsNil(o.Options) {
		return true
	}

	return false
}

// SetOptions gets a reference to the given map[string]interface{} and assigns it to the Options field.
func (o *KnnSearchRequest) SetOptions(v map[string]interface{}) {
	o.Options = v
}

// GetProfile returns the Profile field value if set, zero value otherwise.
func (o *KnnSearchRequest) GetProfile() bool {
	if o == nil || IsNil(o.Profile) {
		var ret bool
		return ret
	}
	return *o.Profile
}

// GetProfileOk returns a tuple with the Profile field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KnnSearchRequest) GetProfileOk() (*bool, bool) {
	if o == nil || IsNil(o.Profile) {
		return nil, false
	}
	return o.Profile, true
}

// HasProfile returns a boolean if a field has been set.
func (o *KnnSearchRequest) HasProfile() bool {
	if o != nil && !IsNil(o.Profile) {
		return true
	}

	return false
}

// SetProfile gets a reference to the given bool and assigns it to the Profile field.
func (o *KnnSearchRequest) SetProfile(v bool) {
	o.Profile = &v
}

// GetSort returns the Sort field value if set, zero value otherwise.
func (o *KnnSearchRequest) GetSort() []SearchRequestParametersSortInner {
	if o == nil || IsNil(o.Sort) {
		var ret []SearchRequestParametersSortInner
		return ret
	}
	return o.Sort
}

// GetSortOk returns a tuple with the Sort field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KnnSearchRequest) GetSortOk() ([]SearchRequestParametersSortInner, bool) {
	if o == nil || IsNil(o.Sort) {
		return nil, false
	}
	return o.Sort, true
}

// HasSort returns a boolean if a field has been set.
func (o *KnnSearchRequest) HasSort() bool {
	if o != nil && !IsNil(o.Sort) {
		return true
	}

	return false
}

// SetSort gets a reference to the given []SearchRequestParametersSortInner and assigns it to the Sort field.
func (o *KnnSearchRequest) SetSort(v []SearchRequestParametersSortInner) {
	o.Sort = v
}

// GetSource returns the Source field value if set, zero value otherwise.
func (o *KnnSearchRequest) GetSource() SearchRequestParametersSource {
	if o == nil || IsNil(o.Source) {
		var ret SearchRequestParametersSource
		return ret
	}
	return *o.Source
}

// GetSourceOk returns a tuple with the Source field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KnnSearchRequest) GetSourceOk() (*SearchRequestParametersSource, bool) {
	if o == nil || IsNil(o.Source) {
		return nil, false
	}
	return o.Source, true
}

// HasSource returns a boolean if a field has been set.
func (o *KnnSearchRequest) HasSource() bool {
	if o != nil && !IsNil(o.Source) {
		return true
	}

	return false
}

// SetSource gets a reference to the given SearchRequestParametersSource and assigns it to the Source field.
func (o *KnnSearchRequest) SetSource(v SearchRequestParametersSource) {
	o.Source = &v
}

// GetTrackScores returns the TrackScores field value if set, zero value otherwise.
func (o *KnnSearchRequest) GetTrackScores() bool {
	if o == nil || IsNil(o.TrackScores) {
		var ret bool
		return ret
	}
	return *o.TrackScores
}

// GetTrackScoresOk returns a tuple with the TrackScores field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KnnSearchRequest) GetTrackScoresOk() (*bool, bool) {
	if o == nil || IsNil(o.TrackScores) {
		return nil, false
	}
	return o.TrackScores, true
}

// HasTrackScores returns a boolean if a field has been set.
func (o *KnnSearchRequest) HasTrackScores() bool {
	if o != nil && !IsNil(o.TrackScores) {
		return true
	}

	return false
}

// SetTrackScores gets a reference to the given bool and assigns it to the TrackScores field.
func (o *KnnSearchRequest) SetTrackScores(v bool) {
	o.TrackScores = &v
}

// GetKnn returns the Knn field value
func (o *KnnSearchRequest) GetKnn() KnnSearchRequestAllOfKnn {
	if o == nil {
		var ret KnnSearchRequestAllOfKnn
		return ret
	}

	return o.Knn
}

// GetKnnOk returns a tuple with the Knn field value
// and a boolean to check if the value has been set.
func (o *KnnSearchRequest) GetKnnOk() (*KnnSearchRequestAllOfKnn, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Knn, true
}

// SetKnn sets field value
func (o *KnnSearchRequest) SetKnn(v KnnSearchRequestAllOfKnn) {
	o.Knn = v
}

func (o KnnSearchRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o KnnSearchRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Aggs) {
		toSerialize["aggs"] = o.Aggs
	}
	if !IsNil(o.Expressions) {
		toSerialize["expressions"] = o.Expressions
	}
	if !IsNil(o.Join) {
		toSerialize["join"] = o.Join
	}
	if !IsNil(o.Highlight) {
		toSerialize["highlight"] = o.Highlight
	}
	toSerialize["index"] = o.Index
	if !IsNil(o.Limit) {
		toSerialize["limit"] = o.Limit
	}
	if !IsNil(o.MaxMatches) {
		toSerialize["max_matches"] = o.MaxMatches
	}
	if !IsNil(o.Offset) {
		toSerialize["offset"] = o.Offset
	}
	if !IsNil(o.Options) {
		toSerialize["options"] = o.Options
	}
	if !IsNil(o.Profile) {
		toSerialize["profile"] = o.Profile
	}
	if !IsNil(o.Sort) {
		toSerialize["sort"] = o.Sort
	}
	if !IsNil(o.Source) {
		toSerialize["_source"] = o.Source
	}
	if !IsNil(o.TrackScores) {
		toSerialize["track_scores"] = o.TrackScores
	}
	toSerialize["knn"] = o.Knn
	return toSerialize, nil
}

func (o *KnnSearchRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"index",
		"knn",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varKnnSearchRequest := _KnnSearchRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varKnnSearchRequest)

	if err != nil {
		return err
	}

	*o = KnnSearchRequest(varKnnSearchRequest)

	return err
}

type NullableKnnSearchRequest struct {
	value *KnnSearchRequest
	isSet bool
}

func (v NullableKnnSearchRequest) Get() *KnnSearchRequest {
	return v.value
}

func (v *NullableKnnSearchRequest) Set(val *KnnSearchRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableKnnSearchRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableKnnSearchRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKnnSearchRequest(val *KnnSearchRequest) *NullableKnnSearchRequest {
	return &NullableKnnSearchRequest{value: val, isSet: true}
}

func (v NullableKnnSearchRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKnnSearchRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


