/*
Manticore Search Client

Сlient for Manticore Search. 

API version: 5.0.0
Contact: info@manticoresearch.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the SuccessResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SuccessResponse{}

// SuccessResponse Response object indicating the success of an operation, such as inserting or updating a document
type SuccessResponse struct {
	// Name of the document table
	Table interface{} `json:"table"` 
	// ID of the document affected by the request operation
	Id interface{} `json:"id"` 
	// Indicates whether the document was created as a result of the operation
	Created interface{} `json:"created"` 
	// Result of the operation, typically 'created', 'updated', or 'deleted'
	Result interface{} `json:"result"` 
	// Indicates whether the document was found in the table
	Found interface{} `json:"found"` 
	// HTTP status code representing the result of the operation
	Status interface{} `json:"status"` 
}

// NewSuccessResponse instantiates a new SuccessResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSuccessResponse() *SuccessResponse {
	this := SuccessResponse{}
	return &this
}

// NewSuccessResponseWithDefaults instantiates a new SuccessResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSuccessResponseWithDefaults() *SuccessResponse {
	this := SuccessResponse{}
	return &this
}

// GetTable returns the Table field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SuccessResponse) GetTable() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Table
}

// GetTableOk returns a tuple with the Table field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SuccessResponse) GetTableOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Table) {
		return nil, false
	}
	return &o.Table, true
}

// HasTable returns a boolean if a field has been set.
func (o *SuccessResponse) HasTable() bool {
	if o != nil && !IsNil(o.Table) {
		return true
	}

	return false
}

// SetTable gets a reference to the given interface{} and assigns it to the Table field.
func (o *SuccessResponse) SetTable(v interface{}) {
	o.Table = v
}

// GetId returns the Id field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SuccessResponse) GetId() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SuccessResponse) GetIdOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return &o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *SuccessResponse) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given interface{} and assigns it to the Id field.
func (o *SuccessResponse) SetId(v interface{}) {
	o.Id = v
}

// GetCreated returns the Created field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SuccessResponse) GetCreated() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Created
}

// GetCreatedOk returns a tuple with the Created field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SuccessResponse) GetCreatedOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Created) {
		return nil, false
	}
	return &o.Created, true
}

// HasCreated returns a boolean if a field has been set.
func (o *SuccessResponse) HasCreated() bool {
	if o != nil && !IsNil(o.Created) {
		return true
	}

	return false
}

// SetCreated gets a reference to the given interface{} and assigns it to the Created field.
func (o *SuccessResponse) SetCreated(v interface{}) {
	o.Created = v
}

// GetResult returns the Result field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SuccessResponse) GetResult() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Result
}

// GetResultOk returns a tuple with the Result field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SuccessResponse) GetResultOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Result) {
		return nil, false
	}
	return &o.Result, true
}

// HasResult returns a boolean if a field has been set.
func (o *SuccessResponse) HasResult() bool {
	if o != nil && !IsNil(o.Result) {
		return true
	}

	return false
}

// SetResult gets a reference to the given interface{} and assigns it to the Result field.
func (o *SuccessResponse) SetResult(v interface{}) {
	o.Result = v
}

// GetFound returns the Found field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SuccessResponse) GetFound() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Found
}

// GetFoundOk returns a tuple with the Found field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SuccessResponse) GetFoundOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Found) {
		return nil, false
	}
	return &o.Found, true
}

// HasFound returns a boolean if a field has been set.
func (o *SuccessResponse) HasFound() bool {
	if o != nil && !IsNil(o.Found) {
		return true
	}

	return false
}

// SetFound gets a reference to the given interface{} and assigns it to the Found field.
func (o *SuccessResponse) SetFound(v interface{}) {
	o.Found = v
}

// GetStatus returns the Status field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SuccessResponse) GetStatus() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SuccessResponse) GetStatusOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return &o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *SuccessResponse) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given interface{} and assigns it to the Status field.
func (o *SuccessResponse) SetStatus(v interface{}) {
	o.Status = v
}

func (o SuccessResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SuccessResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Table != nil {
		toSerialize["table"] = o.Table
	}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.Created != nil {
		toSerialize["created"] = o.Created
	}
	if o.Result != nil {
		toSerialize["result"] = o.Result
	}
	if o.Found != nil {
		toSerialize["found"] = o.Found
	}
	if o.Status != nil {
		toSerialize["status"] = o.Status
	}
	return toSerialize, nil
}

type NullableSuccessResponse struct {
	value *SuccessResponse
	isSet bool
}

func (v NullableSuccessResponse) Get() *SuccessResponse {
	return v.value
}

func (v *NullableSuccessResponse) Set(val *SuccessResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableSuccessResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableSuccessResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSuccessResponse(val *SuccessResponse) *NullableSuccessResponse {
	return &NullableSuccessResponse{value: val, isSet: true}
}

func (v NullableSuccessResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSuccessResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


