/*
Manticore Search Client

Сlient for Manticore Search. 

API version: 5.0.0
Contact: info@manticoresearch.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AggPercentiles type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AggPercentiles{}

// AggPercentiles Object to use percentile values in aggregation. For more information see [Grouping](https://manual.manticoresearch.com/Searching/Grouping#PERCENTILES(),-PERCENTILE_RANKS(),-MEDIAN_ABSOLUTE_DEVIATION()) 
type AggPercentiles struct {
	// Numeric field to calculate percentiles for
	Field string `json:"field"`
	// Percentile points to compute (0-100). Defaults to 1, 5, 25, 50, 75, 95, and 99 when omitted. 
	Values []float32 `json:"values,omitempty"`
	// Return an object keyed by percentile when true, or an array when false. Default is false. 
	Keyed *bool `json:"keyed,omitempty"`
	Tdigest *AggTDigest `json:"tdigest,omitempty"`
}

type _AggPercentiles AggPercentiles

// NewAggPercentiles instantiates a new AggPercentiles object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAggPercentiles(field string) *AggPercentiles {
	this := AggPercentiles{}
	this.Field = field
	return &this
}

// NewAggPercentilesWithDefaults instantiates a new AggPercentiles object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAggPercentilesWithDefaults() *AggPercentiles {
	this := AggPercentiles{}
	return &this
}

// GetField returns the Field field value
func (o *AggPercentiles) GetField() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Field
}

// GetFieldOk returns a tuple with the Field field value
// and a boolean to check if the value has been set.
func (o *AggPercentiles) GetFieldOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Field, true
}

// SetField sets field value
func (o *AggPercentiles) SetField(v string) {
	o.Field = v
}

// GetValues returns the Values field value if set, zero value otherwise.
func (o *AggPercentiles) GetValues() []float32 {
	if o == nil || IsNil(o.Values) {
		var ret []float32
		return ret
	}
	return o.Values
}

// GetValuesOk returns a tuple with the Values field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AggPercentiles) GetValuesOk() ([]float32, bool) {
	if o == nil || IsNil(o.Values) {
		return nil, false
	}
	return o.Values, true
}

// HasValues returns a boolean if a field has been set.
func (o *AggPercentiles) HasValues() bool {
	if o != nil && !IsNil(o.Values) {
		return true
	}

	return false
}

// SetValues gets a reference to the given []float32 and assigns it to the Values field.
func (o *AggPercentiles) SetValues(v []float32) {
	o.Values = v
}

// GetKeyed returns the Keyed field value if set, zero value otherwise.
func (o *AggPercentiles) GetKeyed() bool {
	if o == nil || IsNil(o.Keyed) {
		var ret bool
		return ret
	}
	return *o.Keyed
}

// GetKeyedOk returns a tuple with the Keyed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AggPercentiles) GetKeyedOk() (*bool, bool) {
	if o == nil || IsNil(o.Keyed) {
		return nil, false
	}
	return o.Keyed, true
}

// HasKeyed returns a boolean if a field has been set.
func (o *AggPercentiles) HasKeyed() bool {
	if o != nil && !IsNil(o.Keyed) {
		return true
	}

	return false
}

// SetKeyed gets a reference to the given bool and assigns it to the Keyed field.
func (o *AggPercentiles) SetKeyed(v bool) {
	o.Keyed = &v
}

// GetTdigest returns the Tdigest field value if set, zero value otherwise.
func (o *AggPercentiles) GetTdigest() AggTDigest {
	if o == nil || IsNil(o.Tdigest) {
		var ret AggTDigest
		return ret
	}
	return *o.Tdigest
}

// GetTdigestOk returns a tuple with the Tdigest field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AggPercentiles) GetTdigestOk() (*AggTDigest, bool) {
	if o == nil || IsNil(o.Tdigest) {
		return nil, false
	}
	return o.Tdigest, true
}

// HasTdigest returns a boolean if a field has been set.
func (o *AggPercentiles) HasTdigest() bool {
	if o != nil && !IsNil(o.Tdigest) {
		return true
	}

	return false
}

// SetTdigest gets a reference to the given AggTDigest and assigns it to the Tdigest field.
func (o *AggPercentiles) SetTdigest(v AggTDigest) {
	o.Tdigest = &v
}

func (o AggPercentiles) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AggPercentiles) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["field"] = o.Field
	if !IsNil(o.Values) {
		toSerialize["values"] = o.Values
	}
	if !IsNil(o.Keyed) {
		toSerialize["keyed"] = o.Keyed
	}
	if !IsNil(o.Tdigest) {
		toSerialize["tdigest"] = o.Tdigest
	}
	return toSerialize, nil
}

func (o *AggPercentiles) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"field",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAggPercentiles := _AggPercentiles{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAggPercentiles)

	if err != nil {
		return err
	}

	*o = AggPercentiles(varAggPercentiles)

	return err
}

type NullableAggPercentiles struct {
	value *AggPercentiles
	isSet bool
}

func (v NullableAggPercentiles) Get() *AggPercentiles {
	return v.value
}

func (v *NullableAggPercentiles) Set(val *AggPercentiles) {
	v.value = val
	v.isSet = true
}

func (v NullableAggPercentiles) IsSet() bool {
	return v.isSet
}

func (v *NullableAggPercentiles) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAggPercentiles(val *AggPercentiles) *NullableAggPercentiles {
	return &NullableAggPercentiles{value: val, isSet: true}
}

func (v NullableAggPercentiles) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAggPercentiles) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

