/*
Manticore Search Client

Сlient for Manticore Search. 

API version: 5.0.0
Contact: info@manticoresearch.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// HighlightFields - List of fields available for highlighting
type HighlightFields struct {
	ArrayOfString *[]string
	MapmapOfStringAny *map[string]interface{}
}

// []stringAsHighlightFields is a convenience function that returns []string wrapped in HighlightFields
func ArrayOfStringAsHighlightFields(v *[]string) HighlightFields {
	return HighlightFields{
		ArrayOfString: v,
	}
}

// map[string]interface{}AsHighlightFields is a convenience function that returns map[string]interface{} wrapped in HighlightFields
func MapmapOfStringAnyAsHighlightFields(v *map[string]interface{}) HighlightFields {
	return HighlightFields{
		MapmapOfStringAny: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *HighlightFields) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into ArrayOfString
	err = newStrictDecoder(data).Decode(&dst.ArrayOfString)
	if err == nil {
		jsonArrayOfString, _ := json.Marshal(dst.ArrayOfString)
		if string(jsonArrayOfString) == "{}" { // empty struct
			dst.ArrayOfString = nil
		} else {
			if err = validator.Validate(dst.ArrayOfString); err != nil {
				dst.ArrayOfString = nil
			} else {
				match++
			}
		}
	} else {
		dst.ArrayOfString = nil
	}

	// try to unmarshal data into MapmapOfStringAny
	err = newStrictDecoder(data).Decode(&dst.MapmapOfStringAny)
	if err == nil {
		jsonMapmapOfStringAny, _ := json.Marshal(dst.MapmapOfStringAny)
		if string(jsonMapmapOfStringAny) == "{}" { // empty struct
			dst.MapmapOfStringAny = nil
		} else {
			if err = validator.Validate(dst.MapmapOfStringAny); err != nil {
				dst.MapmapOfStringAny = nil
			} else {
				match++
			}
		}
	} else {
		dst.MapmapOfStringAny = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.ArrayOfString = nil
		dst.MapmapOfStringAny = nil

		return fmt.Errorf("data matches more than one schema in oneOf(HighlightFields)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(HighlightFields)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src HighlightFields) MarshalJSON() ([]byte, error) {
	if src.ArrayOfString != nil {
		return json.Marshal(&src.ArrayOfString)
	}

	if src.MapmapOfStringAny != nil {
		return json.Marshal(&src.MapmapOfStringAny)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *HighlightFields) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.ArrayOfString != nil {
		return obj.ArrayOfString
	}

	if obj.MapmapOfStringAny != nil {
		return obj.MapmapOfStringAny
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj HighlightFields) GetActualInstanceValue() (interface{}) {
	if obj.ArrayOfString != nil {
		return *obj.ArrayOfString
	}

	if obj.MapmapOfStringAny != nil {
		return *obj.MapmapOfStringAny
	}

	// all schemas are nil
	return nil
}

type NullableHighlightFields struct {
	value *HighlightFields
	isSet bool
}

func (v NullableHighlightFields) Get() *HighlightFields {
	return v.value
}

func (v *NullableHighlightFields) Set(val *HighlightFields) {
	v.value = val
	v.isSet = true
}

func (v NullableHighlightFields) IsSet() bool {
	return v.isSet
}

func (v *NullableHighlightFields) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHighlightFields(val *HighlightFields) *NullableHighlightFields {
	return &NullableHighlightFields{value: val, isSet: true}
}

func (v NullableHighlightFields) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHighlightFields) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


