/*
Manticore Search Client

Сlient for Manticore Search. 

API version: 5.0.0
Contact: info@manticoresearch.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the Highlight type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Highlight{}

// Highlight struct for Highlight
type Highlight struct {
	// Maximum size of the text fragments in highlighted snippets per field
	FragmentSize interface{} `json:"fragment_size"` 
	// Maximum size of snippets per field
	Limit interface{} `json:"limit"` 
	// Maximum number of snippets per field
	LimitSnippets interface{} `json:"limit_snippets"` 
	// Maximum number of words per field
	LimitWords interface{} `json:"limit_words"` 
	// Total number of highlighted fragments per field
	NumberOfFragments interface{} `json:"number_of_fragments"` 
	// Text inserted after the matched term, typically used for HTML formatting
	AfterMatch interface{} `json:"after_match"` 
	// Permits an empty string to be returned as the highlighting result. Otherwise, the beginning of the original text would be returned
	AllowEmpty interface{} `json:"allow_empty"` 
	// Number of words around the match to include in the highlight
	Around interface{} `json:"around"` 
	// Text inserted before the match, typically used for HTML formatting
	BeforeMatch interface{} `json:"before_match"` 
	// Emits an HTML tag with the enclosing zone name before each highlighted snippet
	EmitZones interface{} `json:"emit_zones"` 
	// If set to 'html', retains HTML markup when highlighting
	Encoder interface{} `json:"encoder"` 
	Fields *HighlightFields `json:"fields"` 
	// Ignores the length limit until the result includes all keywords
	ForceAllWords interface{} `json:"force_all_words"` 
	// Forces snippet generation even if limits allow highlighting the entire text
	ForceSnippets interface{} `json:"force_snippets"` 
	HighlightQuery *HighlightAllOfHighlightQuery `json:"highlight_query"` 
	// Defines the mode for handling HTML markup in the highlight
	HtmlStripMode interface{} `json:"html_strip_mode"` 
	// Determines whether the 'limit', 'limit_words', and 'limit_snippets' options operate as individual limits in each field of the document
	LimitsPerField interface{} `json:"limits_per_field"` 
	// If set to 1, allows an empty string to be returned as a highlighting result
	NoMatchSize interface{} `json:"no_match_size"` 
	// Sets the sorting order of highlighted snippets
	Order interface{} `json:"order"` 
	// Text inserted before each highlighted snippet
	PreTags interface{} `json:"pre_tags"` 
	// Text inserted after each highlighted snippet
	PostTags interface{} `json:"post_tags"` 
	// Sets the starting value of the %SNIPPET_ID% macro
	StartSnippetId interface{} `json:"start_snippet_id"` 
	// Defines whether to additionally break snippets by phrase boundary characters
	UseBoundaries interface{} `json:"use_boundaries"` 
}

// NewHighlight instantiates a new Highlight object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHighlight() *Highlight {
	this := Highlight{}
	return &this
}

// NewHighlightWithDefaults instantiates a new Highlight object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHighlightWithDefaults() *Highlight {
	this := Highlight{}
	return &this
}

// GetFragmentSize returns the FragmentSize field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Highlight) GetFragmentSize() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.FragmentSize
}

// GetFragmentSizeOk returns a tuple with the FragmentSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Highlight) GetFragmentSizeOk() (*interface{}, bool) {
	if o == nil || IsNil(o.FragmentSize) {
		return nil, false
	}
	return &o.FragmentSize, true
}

// HasFragmentSize returns a boolean if a field has been set.
func (o *Highlight) HasFragmentSize() bool {
	if o != nil && !IsNil(o.FragmentSize) {
		return true
	}

	return false
}

// SetFragmentSize gets a reference to the given interface{} and assigns it to the FragmentSize field.
func (o *Highlight) SetFragmentSize(v interface{}) {
	o.FragmentSize = v
}

// GetLimit returns the Limit field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Highlight) GetLimit() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Limit
}

// GetLimitOk returns a tuple with the Limit field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Highlight) GetLimitOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Limit) {
		return nil, false
	}
	return &o.Limit, true
}

// HasLimit returns a boolean if a field has been set.
func (o *Highlight) HasLimit() bool {
	if o != nil && !IsNil(o.Limit) {
		return true
	}

	return false
}

// SetLimit gets a reference to the given interface{} and assigns it to the Limit field.
func (o *Highlight) SetLimit(v interface{}) {
	o.Limit = v
}

// GetLimitSnippets returns the LimitSnippets field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Highlight) GetLimitSnippets() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.LimitSnippets
}

// GetLimitSnippetsOk returns a tuple with the LimitSnippets field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Highlight) GetLimitSnippetsOk() (*interface{}, bool) {
	if o == nil || IsNil(o.LimitSnippets) {
		return nil, false
	}
	return &o.LimitSnippets, true
}

// HasLimitSnippets returns a boolean if a field has been set.
func (o *Highlight) HasLimitSnippets() bool {
	if o != nil && !IsNil(o.LimitSnippets) {
		return true
	}

	return false
}

// SetLimitSnippets gets a reference to the given interface{} and assigns it to the LimitSnippets field.
func (o *Highlight) SetLimitSnippets(v interface{}) {
	o.LimitSnippets = v
}

// GetLimitWords returns the LimitWords field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Highlight) GetLimitWords() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.LimitWords
}

// GetLimitWordsOk returns a tuple with the LimitWords field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Highlight) GetLimitWordsOk() (*interface{}, bool) {
	if o == nil || IsNil(o.LimitWords) {
		return nil, false
	}
	return &o.LimitWords, true
}

// HasLimitWords returns a boolean if a field has been set.
func (o *Highlight) HasLimitWords() bool {
	if o != nil && !IsNil(o.LimitWords) {
		return true
	}

	return false
}

// SetLimitWords gets a reference to the given interface{} and assigns it to the LimitWords field.
func (o *Highlight) SetLimitWords(v interface{}) {
	o.LimitWords = v
}

// GetNumberOfFragments returns the NumberOfFragments field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Highlight) GetNumberOfFragments() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.NumberOfFragments
}

// GetNumberOfFragmentsOk returns a tuple with the NumberOfFragments field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Highlight) GetNumberOfFragmentsOk() (*interface{}, bool) {
	if o == nil || IsNil(o.NumberOfFragments) {
		return nil, false
	}
	return &o.NumberOfFragments, true
}

// HasNumberOfFragments returns a boolean if a field has been set.
func (o *Highlight) HasNumberOfFragments() bool {
	if o != nil && !IsNil(o.NumberOfFragments) {
		return true
	}

	return false
}

// SetNumberOfFragments gets a reference to the given interface{} and assigns it to the NumberOfFragments field.
func (o *Highlight) SetNumberOfFragments(v interface{}) {
	o.NumberOfFragments = v
}

// GetAfterMatch returns the AfterMatch field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Highlight) GetAfterMatch() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.AfterMatch
}

// GetAfterMatchOk returns a tuple with the AfterMatch field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Highlight) GetAfterMatchOk() (*interface{}, bool) {
	if o == nil || IsNil(o.AfterMatch) {
		return nil, false
	}
	return &o.AfterMatch, true
}

// HasAfterMatch returns a boolean if a field has been set.
func (o *Highlight) HasAfterMatch() bool {
	if o != nil && !IsNil(o.AfterMatch) {
		return true
	}

	return false
}

// SetAfterMatch gets a reference to the given interface{} and assigns it to the AfterMatch field.
func (o *Highlight) SetAfterMatch(v interface{}) {
	o.AfterMatch = v
}

// GetAllowEmpty returns the AllowEmpty field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Highlight) GetAllowEmpty() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.AllowEmpty
}

// GetAllowEmptyOk returns a tuple with the AllowEmpty field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Highlight) GetAllowEmptyOk() (*interface{}, bool) {
	if o == nil || IsNil(o.AllowEmpty) {
		return nil, false
	}
	return &o.AllowEmpty, true
}

// HasAllowEmpty returns a boolean if a field has been set.
func (o *Highlight) HasAllowEmpty() bool {
	if o != nil && !IsNil(o.AllowEmpty) {
		return true
	}

	return false
}

// SetAllowEmpty gets a reference to the given interface{} and assigns it to the AllowEmpty field.
func (o *Highlight) SetAllowEmpty(v interface{}) {
	o.AllowEmpty = v
}

// GetAround returns the Around field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Highlight) GetAround() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Around
}

// GetAroundOk returns a tuple with the Around field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Highlight) GetAroundOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Around) {
		return nil, false
	}
	return &o.Around, true
}

// HasAround returns a boolean if a field has been set.
func (o *Highlight) HasAround() bool {
	if o != nil && !IsNil(o.Around) {
		return true
	}

	return false
}

// SetAround gets a reference to the given interface{} and assigns it to the Around field.
func (o *Highlight) SetAround(v interface{}) {
	o.Around = v
}

// GetBeforeMatch returns the BeforeMatch field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Highlight) GetBeforeMatch() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.BeforeMatch
}

// GetBeforeMatchOk returns a tuple with the BeforeMatch field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Highlight) GetBeforeMatchOk() (*interface{}, bool) {
	if o == nil || IsNil(o.BeforeMatch) {
		return nil, false
	}
	return &o.BeforeMatch, true
}

// HasBeforeMatch returns a boolean if a field has been set.
func (o *Highlight) HasBeforeMatch() bool {
	if o != nil && !IsNil(o.BeforeMatch) {
		return true
	}

	return false
}

// SetBeforeMatch gets a reference to the given interface{} and assigns it to the BeforeMatch field.
func (o *Highlight) SetBeforeMatch(v interface{}) {
	o.BeforeMatch = v
}

// GetEmitZones returns the EmitZones field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Highlight) GetEmitZones() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.EmitZones
}

// GetEmitZonesOk returns a tuple with the EmitZones field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Highlight) GetEmitZonesOk() (*interface{}, bool) {
	if o == nil || IsNil(o.EmitZones) {
		return nil, false
	}
	return &o.EmitZones, true
}

// HasEmitZones returns a boolean if a field has been set.
func (o *Highlight) HasEmitZones() bool {
	if o != nil && !IsNil(o.EmitZones) {
		return true
	}

	return false
}

// SetEmitZones gets a reference to the given interface{} and assigns it to the EmitZones field.
func (o *Highlight) SetEmitZones(v interface{}) {
	o.EmitZones = v
}

// GetEncoder returns the Encoder field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Highlight) GetEncoder() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Encoder
}

// GetEncoderOk returns a tuple with the Encoder field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Highlight) GetEncoderOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Encoder) {
		return nil, false
	}
	return &o.Encoder, true
}

// HasEncoder returns a boolean if a field has been set.
func (o *Highlight) HasEncoder() bool {
	if o != nil && !IsNil(o.Encoder) {
		return true
	}

	return false
}

// SetEncoder gets a reference to the given interface{} and assigns it to the Encoder field.
func (o *Highlight) SetEncoder(v interface{}) {
	o.Encoder = v
}

// GetFields returns the Fields field value if set, zero value otherwise.
func (o *Highlight) GetFields() HighlightFields {
	if o == nil || IsNil(o.Fields) {
		var ret HighlightFields
		return ret
	}
	return *o.Fields
}

// GetFieldsOk returns a tuple with the Fields field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Highlight) GetFieldsOk() (*HighlightFields, bool) {
	if o == nil || IsNil(o.Fields) {
		return nil, false
	}
	return o.Fields, true
}

// HasFields returns a boolean if a field has been set.
func (o *Highlight) HasFields() bool {
	if o != nil && !IsNil(o.Fields) {
		return true
	}

	return false
}

// SetFields gets a reference to the given HighlightFields and assigns it to the Fields field.
func (o *Highlight) SetFields(v HighlightFields) {
	o.Fields = &v
}

// GetForceAllWords returns the ForceAllWords field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Highlight) GetForceAllWords() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.ForceAllWords
}

// GetForceAllWordsOk returns a tuple with the ForceAllWords field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Highlight) GetForceAllWordsOk() (*interface{}, bool) {
	if o == nil || IsNil(o.ForceAllWords) {
		return nil, false
	}
	return &o.ForceAllWords, true
}

// HasForceAllWords returns a boolean if a field has been set.
func (o *Highlight) HasForceAllWords() bool {
	if o != nil && !IsNil(o.ForceAllWords) {
		return true
	}

	return false
}

// SetForceAllWords gets a reference to the given interface{} and assigns it to the ForceAllWords field.
func (o *Highlight) SetForceAllWords(v interface{}) {
	o.ForceAllWords = v
}

// GetForceSnippets returns the ForceSnippets field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Highlight) GetForceSnippets() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.ForceSnippets
}

// GetForceSnippetsOk returns a tuple with the ForceSnippets field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Highlight) GetForceSnippetsOk() (*interface{}, bool) {
	if o == nil || IsNil(o.ForceSnippets) {
		return nil, false
	}
	return &o.ForceSnippets, true
}

// HasForceSnippets returns a boolean if a field has been set.
func (o *Highlight) HasForceSnippets() bool {
	if o != nil && !IsNil(o.ForceSnippets) {
		return true
	}

	return false
}

// SetForceSnippets gets a reference to the given interface{} and assigns it to the ForceSnippets field.
func (o *Highlight) SetForceSnippets(v interface{}) {
	o.ForceSnippets = v
}

// GetHighlightQuery returns the HighlightQuery field value if set, zero value otherwise.
func (o *Highlight) GetHighlightQuery() HighlightAllOfHighlightQuery {
	if o == nil || IsNil(o.HighlightQuery) {
		var ret HighlightAllOfHighlightQuery
		return ret
	}
	return *o.HighlightQuery
}

// GetHighlightQueryOk returns a tuple with the HighlightQuery field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Highlight) GetHighlightQueryOk() (*HighlightAllOfHighlightQuery, bool) {
	if o == nil || IsNil(o.HighlightQuery) {
		return nil, false
	}
	return o.HighlightQuery, true
}

// HasHighlightQuery returns a boolean if a field has been set.
func (o *Highlight) HasHighlightQuery() bool {
	if o != nil && !IsNil(o.HighlightQuery) {
		return true
	}

	return false
}

// SetHighlightQuery gets a reference to the given HighlightAllOfHighlightQuery and assigns it to the HighlightQuery field.
func (o *Highlight) SetHighlightQuery(v HighlightAllOfHighlightQuery) {
	o.HighlightQuery = &v
}

// GetHtmlStripMode returns the HtmlStripMode field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Highlight) GetHtmlStripMode() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.HtmlStripMode
}

// GetHtmlStripModeOk returns a tuple with the HtmlStripMode field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Highlight) GetHtmlStripModeOk() (*interface{}, bool) {
	if o == nil || IsNil(o.HtmlStripMode) {
		return nil, false
	}
	return &o.HtmlStripMode, true
}

// HasHtmlStripMode returns a boolean if a field has been set.
func (o *Highlight) HasHtmlStripMode() bool {
	if o != nil && !IsNil(o.HtmlStripMode) {
		return true
	}

	return false
}

// SetHtmlStripMode gets a reference to the given interface{} and assigns it to the HtmlStripMode field.
func (o *Highlight) SetHtmlStripMode(v interface{}) {
	o.HtmlStripMode = v
}

// GetLimitsPerField returns the LimitsPerField field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Highlight) GetLimitsPerField() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.LimitsPerField
}

// GetLimitsPerFieldOk returns a tuple with the LimitsPerField field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Highlight) GetLimitsPerFieldOk() (*interface{}, bool) {
	if o == nil || IsNil(o.LimitsPerField) {
		return nil, false
	}
	return &o.LimitsPerField, true
}

// HasLimitsPerField returns a boolean if a field has been set.
func (o *Highlight) HasLimitsPerField() bool {
	if o != nil && !IsNil(o.LimitsPerField) {
		return true
	}

	return false
}

// SetLimitsPerField gets a reference to the given interface{} and assigns it to the LimitsPerField field.
func (o *Highlight) SetLimitsPerField(v interface{}) {
	o.LimitsPerField = v
}

// GetNoMatchSize returns the NoMatchSize field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Highlight) GetNoMatchSize() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.NoMatchSize
}

// GetNoMatchSizeOk returns a tuple with the NoMatchSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Highlight) GetNoMatchSizeOk() (*interface{}, bool) {
	if o == nil || IsNil(o.NoMatchSize) {
		return nil, false
	}
	return &o.NoMatchSize, true
}

// HasNoMatchSize returns a boolean if a field has been set.
func (o *Highlight) HasNoMatchSize() bool {
	if o != nil && !IsNil(o.NoMatchSize) {
		return true
	}

	return false
}

// SetNoMatchSize gets a reference to the given interface{} and assigns it to the NoMatchSize field.
func (o *Highlight) SetNoMatchSize(v interface{}) {
	o.NoMatchSize = v
}

// GetOrder returns the Order field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Highlight) GetOrder() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Order
}

// GetOrderOk returns a tuple with the Order field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Highlight) GetOrderOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Order) {
		return nil, false
	}
	return &o.Order, true
}

// HasOrder returns a boolean if a field has been set.
func (o *Highlight) HasOrder() bool {
	if o != nil && !IsNil(o.Order) {
		return true
	}

	return false
}

// SetOrder gets a reference to the given interface{} and assigns it to the Order field.
func (o *Highlight) SetOrder(v interface{}) {
	o.Order = v
}

// GetPreTags returns the PreTags field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Highlight) GetPreTags() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.PreTags
}

// GetPreTagsOk returns a tuple with the PreTags field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Highlight) GetPreTagsOk() (*interface{}, bool) {
	if o == nil || IsNil(o.PreTags) {
		return nil, false
	}
	return &o.PreTags, true
}

// HasPreTags returns a boolean if a field has been set.
func (o *Highlight) HasPreTags() bool {
	if o != nil && !IsNil(o.PreTags) {
		return true
	}

	return false
}

// SetPreTags gets a reference to the given interface{} and assigns it to the PreTags field.
func (o *Highlight) SetPreTags(v interface{}) {
	o.PreTags = v
}

// GetPostTags returns the PostTags field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Highlight) GetPostTags() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.PostTags
}

// GetPostTagsOk returns a tuple with the PostTags field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Highlight) GetPostTagsOk() (*interface{}, bool) {
	if o == nil || IsNil(o.PostTags) {
		return nil, false
	}
	return &o.PostTags, true
}

// HasPostTags returns a boolean if a field has been set.
func (o *Highlight) HasPostTags() bool {
	if o != nil && !IsNil(o.PostTags) {
		return true
	}

	return false
}

// SetPostTags gets a reference to the given interface{} and assigns it to the PostTags field.
func (o *Highlight) SetPostTags(v interface{}) {
	o.PostTags = v
}

// GetStartSnippetId returns the StartSnippetId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Highlight) GetStartSnippetId() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.StartSnippetId
}

// GetStartSnippetIdOk returns a tuple with the StartSnippetId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Highlight) GetStartSnippetIdOk() (*interface{}, bool) {
	if o == nil || IsNil(o.StartSnippetId) {
		return nil, false
	}
	return &o.StartSnippetId, true
}

// HasStartSnippetId returns a boolean if a field has been set.
func (o *Highlight) HasStartSnippetId() bool {
	if o != nil && !IsNil(o.StartSnippetId) {
		return true
	}

	return false
}

// SetStartSnippetId gets a reference to the given interface{} and assigns it to the StartSnippetId field.
func (o *Highlight) SetStartSnippetId(v interface{}) {
	o.StartSnippetId = v
}

// GetUseBoundaries returns the UseBoundaries field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Highlight) GetUseBoundaries() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.UseBoundaries
}

// GetUseBoundariesOk returns a tuple with the UseBoundaries field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Highlight) GetUseBoundariesOk() (*interface{}, bool) {
	if o == nil || IsNil(o.UseBoundaries) {
		return nil, false
	}
	return &o.UseBoundaries, true
}

// HasUseBoundaries returns a boolean if a field has been set.
func (o *Highlight) HasUseBoundaries() bool {
	if o != nil && !IsNil(o.UseBoundaries) {
		return true
	}

	return false
}

// SetUseBoundaries gets a reference to the given interface{} and assigns it to the UseBoundaries field.
func (o *Highlight) SetUseBoundaries(v interface{}) {
	o.UseBoundaries = v
}

func (o Highlight) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Highlight) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.FragmentSize != nil {
		toSerialize["fragment_size"] = o.FragmentSize
	}
	if o.Limit != nil {
		toSerialize["limit"] = o.Limit
	}
	if o.LimitSnippets != nil {
		toSerialize["limit_snippets"] = o.LimitSnippets
	}
	if o.LimitWords != nil {
		toSerialize["limit_words"] = o.LimitWords
	}
	if o.NumberOfFragments != nil {
		toSerialize["number_of_fragments"] = o.NumberOfFragments
	}
	if o.AfterMatch != nil {
		toSerialize["after_match"] = o.AfterMatch
	}
	if o.AllowEmpty != nil {
		toSerialize["allow_empty"] = o.AllowEmpty
	}
	if o.Around != nil {
		toSerialize["around"] = o.Around
	}
	if o.BeforeMatch != nil {
		toSerialize["before_match"] = o.BeforeMatch
	}
	if o.EmitZones != nil {
		toSerialize["emit_zones"] = o.EmitZones
	}
	if o.Encoder != nil {
		toSerialize["encoder"] = o.Encoder
	}
	if !IsNil(o.Fields) {
		toSerialize["fields"] = o.Fields
	}
	if o.ForceAllWords != nil {
		toSerialize["force_all_words"] = o.ForceAllWords
	}
	if o.ForceSnippets != nil {
		toSerialize["force_snippets"] = o.ForceSnippets
	}
	if !IsNil(o.HighlightQuery) {
		toSerialize["highlight_query"] = o.HighlightQuery
	}
	if o.HtmlStripMode != nil {
		toSerialize["html_strip_mode"] = o.HtmlStripMode
	}
	if o.LimitsPerField != nil {
		toSerialize["limits_per_field"] = o.LimitsPerField
	}
	if o.NoMatchSize != nil {
		toSerialize["no_match_size"] = o.NoMatchSize
	}
	if o.Order != nil {
		toSerialize["order"] = o.Order
	}
	if o.PreTags != nil {
		toSerialize["pre_tags"] = o.PreTags
	}
	if o.PostTags != nil {
		toSerialize["post_tags"] = o.PostTags
	}
	if o.StartSnippetId != nil {
		toSerialize["start_snippet_id"] = o.StartSnippetId
	}
	if o.UseBoundaries != nil {
		toSerialize["use_boundaries"] = o.UseBoundaries
	}
	return toSerialize, nil
}

type NullableHighlight struct {
	value *Highlight
	isSet bool
}

func (v NullableHighlight) Get() *Highlight {
	return v.value
}

func (v *NullableHighlight) Set(val *Highlight) {
	v.value = val
	v.isSet = true
}

func (v NullableHighlight) IsSet() bool {
	return v.isSet
}

func (v *NullableHighlight) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHighlight(val *Highlight) *NullableHighlight {
	return &NullableHighlight{value: val, isSet: true}
}

func (v NullableHighlight) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHighlight) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


