/*
Manticore Search Client

Сlient for Manticore Search. 

API version: 5.0.0
Contact: info@manticoresearch.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the SearchResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SearchResponse{}

// SearchResponse Response object containing search results. For conversational search requests that include a `chat` object, the optional chat fields below are also populated. For conversational search response fields see [Conversational search](https://manual.manticoresearch.com/Searching/Conversational_search#Response) 
type SearchResponse struct {
	// Time taken to execute the search
	Took *int32 `json:"took,omitempty"`
	// Indicates whether the search operation timed out
	TimedOut *bool `json:"timed_out,omitempty"`
	// Aggregated search results grouped by the specified criteria. Each named aggregation typically contains a `buckets` array (or keyed map) of bucket objects with `key`, `doc_count`, and optional `status`. 
	Aggregations map[string]AggBucketsResult `json:"aggregations,omitempty"`
	Hits *SearchResponseHits `json:"hits,omitempty"`
	// Profile information about the search execution, if profiling is enabled
	Profile map[string]interface{} `json:"profile,omitempty"`
	// Scroll token to be used fo pagination
	Scroll *string `json:"scroll,omitempty"`
	// Warnings encountered during the search operation
	Warning map[string]interface{} `json:"warning,omitempty"`
	// Existing or generated conversation id (conversational search)
	ConversationUuid *string `json:"conversation_uuid,omitempty"`
	// Original user query (conversational search)
	UserQuery *string `json:"user_query,omitempty"`
	// Standalone search query used for KNN retrieval (conversational search)
	SearchQuery *string `json:"search_query,omitempty"`
	// LLM answer as generated (conversational search)
	Response *string `json:"response,omitempty"`
	// JSON string containing retrieved source rows used as LLM context (conversational search). 
	Sources *string `json:"sources,omitempty"`
}

// NewSearchResponse instantiates a new SearchResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSearchResponse() *SearchResponse {
	this := SearchResponse{}
	return &this
}

// NewSearchResponseWithDefaults instantiates a new SearchResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSearchResponseWithDefaults() *SearchResponse {
	this := SearchResponse{}
	return &this
}

// GetTook returns the Took field value if set, zero value otherwise.
func (o *SearchResponse) GetTook() int32 {
	if o == nil || IsNil(o.Took) {
		var ret int32
		return ret
	}
	return *o.Took
}

// GetTookOk returns a tuple with the Took field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchResponse) GetTookOk() (*int32, bool) {
	if o == nil || IsNil(o.Took) {
		return nil, false
	}
	return o.Took, true
}

// HasTook returns a boolean if a field has been set.
func (o *SearchResponse) HasTook() bool {
	if o != nil && !IsNil(o.Took) {
		return true
	}

	return false
}

// SetTook gets a reference to the given int32 and assigns it to the Took field.
func (o *SearchResponse) SetTook(v int32) {
	o.Took = &v
}

// GetTimedOut returns the TimedOut field value if set, zero value otherwise.
func (o *SearchResponse) GetTimedOut() bool {
	if o == nil || IsNil(o.TimedOut) {
		var ret bool
		return ret
	}
	return *o.TimedOut
}

// GetTimedOutOk returns a tuple with the TimedOut field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchResponse) GetTimedOutOk() (*bool, bool) {
	if o == nil || IsNil(o.TimedOut) {
		return nil, false
	}
	return o.TimedOut, true
}

// HasTimedOut returns a boolean if a field has been set.
func (o *SearchResponse) HasTimedOut() bool {
	if o != nil && !IsNil(o.TimedOut) {
		return true
	}

	return false
}

// SetTimedOut gets a reference to the given bool and assigns it to the TimedOut field.
func (o *SearchResponse) SetTimedOut(v bool) {
	o.TimedOut = &v
}

// GetAggregations returns the Aggregations field value if set, zero value otherwise.
func (o *SearchResponse) GetAggregations() map[string]AggBucketsResult {
	if o == nil || IsNil(o.Aggregations) {
		var ret map[string]AggBucketsResult
		return ret
	}
	return o.Aggregations
}

// GetAggregationsOk returns a tuple with the Aggregations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchResponse) GetAggregationsOk() (map[string]AggBucketsResult, bool) {
	if o == nil || IsNil(o.Aggregations) {
		return map[string]AggBucketsResult{}, false
	}
	return o.Aggregations, true
}

// HasAggregations returns a boolean if a field has been set.
func (o *SearchResponse) HasAggregations() bool {
	if o != nil && !IsNil(o.Aggregations) {
		return true
	}

	return false
}

// SetAggregations gets a reference to the given map[string]AggBucketsResult and assigns it to the Aggregations field.
func (o *SearchResponse) SetAggregations(v map[string]AggBucketsResult) {
	o.Aggregations = v
}

// GetHits returns the Hits field value if set, zero value otherwise.
func (o *SearchResponse) GetHits() SearchResponseHits {
	if o == nil || IsNil(o.Hits) {
		var ret SearchResponseHits
		return ret
	}
	return *o.Hits
}

// GetHitsOk returns a tuple with the Hits field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchResponse) GetHitsOk() (*SearchResponseHits, bool) {
	if o == nil || IsNil(o.Hits) {
		return nil, false
	}
	return o.Hits, true
}

// HasHits returns a boolean if a field has been set.
func (o *SearchResponse) HasHits() bool {
	if o != nil && !IsNil(o.Hits) {
		return true
	}

	return false
}

// SetHits gets a reference to the given SearchResponseHits and assigns it to the Hits field.
func (o *SearchResponse) SetHits(v SearchResponseHits) {
	o.Hits = &v
}

// GetProfile returns the Profile field value if set, zero value otherwise.
func (o *SearchResponse) GetProfile() map[string]interface{} {
	if o == nil || IsNil(o.Profile) {
		var ret map[string]interface{}
		return ret
	}
	return o.Profile
}

// GetProfileOk returns a tuple with the Profile field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchResponse) GetProfileOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Profile) {
		return map[string]interface{}{}, false
	}
	return o.Profile, true
}

// HasProfile returns a boolean if a field has been set.
func (o *SearchResponse) HasProfile() bool {
	if o != nil && !IsNil(o.Profile) {
		return true
	}

	return false
}

// SetProfile gets a reference to the given map[string]interface{} and assigns it to the Profile field.
func (o *SearchResponse) SetProfile(v map[string]interface{}) {
	o.Profile = v
}

// GetScroll returns the Scroll field value if set, zero value otherwise.
func (o *SearchResponse) GetScroll() string {
	if o == nil || IsNil(o.Scroll) {
		var ret string
		return ret
	}
	return *o.Scroll
}

// GetScrollOk returns a tuple with the Scroll field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchResponse) GetScrollOk() (*string, bool) {
	if o == nil || IsNil(o.Scroll) {
		return nil, false
	}
	return o.Scroll, true
}

// HasScroll returns a boolean if a field has been set.
func (o *SearchResponse) HasScroll() bool {
	if o != nil && !IsNil(o.Scroll) {
		return true
	}

	return false
}

// SetScroll gets a reference to the given string and assigns it to the Scroll field.
func (o *SearchResponse) SetScroll(v string) {
	o.Scroll = &v
}

// GetWarning returns the Warning field value if set, zero value otherwise.
func (o *SearchResponse) GetWarning() map[string]interface{} {
	if o == nil || IsNil(o.Warning) {
		var ret map[string]interface{}
		return ret
	}
	return o.Warning
}

// GetWarningOk returns a tuple with the Warning field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchResponse) GetWarningOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Warning) {
		return map[string]interface{}{}, false
	}
	return o.Warning, true
}

// HasWarning returns a boolean if a field has been set.
func (o *SearchResponse) HasWarning() bool {
	if o != nil && !IsNil(o.Warning) {
		return true
	}

	return false
}

// SetWarning gets a reference to the given map[string]interface{} and assigns it to the Warning field.
func (o *SearchResponse) SetWarning(v map[string]interface{}) {
	o.Warning = v
}

// GetConversationUuid returns the ConversationUuid field value if set, zero value otherwise.
func (o *SearchResponse) GetConversationUuid() string {
	if o == nil || IsNil(o.ConversationUuid) {
		var ret string
		return ret
	}
	return *o.ConversationUuid
}

// GetConversationUuidOk returns a tuple with the ConversationUuid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchResponse) GetConversationUuidOk() (*string, bool) {
	if o == nil || IsNil(o.ConversationUuid) {
		return nil, false
	}
	return o.ConversationUuid, true
}

// HasConversationUuid returns a boolean if a field has been set.
func (o *SearchResponse) HasConversationUuid() bool {
	if o != nil && !IsNil(o.ConversationUuid) {
		return true
	}

	return false
}

// SetConversationUuid gets a reference to the given string and assigns it to the ConversationUuid field.
func (o *SearchResponse) SetConversationUuid(v string) {
	o.ConversationUuid = &v
}

// GetUserQuery returns the UserQuery field value if set, zero value otherwise.
func (o *SearchResponse) GetUserQuery() string {
	if o == nil || IsNil(o.UserQuery) {
		var ret string
		return ret
	}
	return *o.UserQuery
}

// GetUserQueryOk returns a tuple with the UserQuery field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchResponse) GetUserQueryOk() (*string, bool) {
	if o == nil || IsNil(o.UserQuery) {
		return nil, false
	}
	return o.UserQuery, true
}

// HasUserQuery returns a boolean if a field has been set.
func (o *SearchResponse) HasUserQuery() bool {
	if o != nil && !IsNil(o.UserQuery) {
		return true
	}

	return false
}

// SetUserQuery gets a reference to the given string and assigns it to the UserQuery field.
func (o *SearchResponse) SetUserQuery(v string) {
	o.UserQuery = &v
}

// GetSearchQuery returns the SearchQuery field value if set, zero value otherwise.
func (o *SearchResponse) GetSearchQuery() string {
	if o == nil || IsNil(o.SearchQuery) {
		var ret string
		return ret
	}
	return *o.SearchQuery
}

// GetSearchQueryOk returns a tuple with the SearchQuery field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchResponse) GetSearchQueryOk() (*string, bool) {
	if o == nil || IsNil(o.SearchQuery) {
		return nil, false
	}
	return o.SearchQuery, true
}

// HasSearchQuery returns a boolean if a field has been set.
func (o *SearchResponse) HasSearchQuery() bool {
	if o != nil && !IsNil(o.SearchQuery) {
		return true
	}

	return false
}

// SetSearchQuery gets a reference to the given string and assigns it to the SearchQuery field.
func (o *SearchResponse) SetSearchQuery(v string) {
	o.SearchQuery = &v
}

// GetResponse returns the Response field value if set, zero value otherwise.
func (o *SearchResponse) GetResponse() string {
	if o == nil || IsNil(o.Response) {
		var ret string
		return ret
	}
	return *o.Response
}

// GetResponseOk returns a tuple with the Response field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchResponse) GetResponseOk() (*string, bool) {
	if o == nil || IsNil(o.Response) {
		return nil, false
	}
	return o.Response, true
}

// HasResponse returns a boolean if a field has been set.
func (o *SearchResponse) HasResponse() bool {
	if o != nil && !IsNil(o.Response) {
		return true
	}

	return false
}

// SetResponse gets a reference to the given string and assigns it to the Response field.
func (o *SearchResponse) SetResponse(v string) {
	o.Response = &v
}

// GetSources returns the Sources field value if set, zero value otherwise.
func (o *SearchResponse) GetSources() string {
	if o == nil || IsNil(o.Sources) {
		var ret string
		return ret
	}
	return *o.Sources
}

// GetSourcesOk returns a tuple with the Sources field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchResponse) GetSourcesOk() (*string, bool) {
	if o == nil || IsNil(o.Sources) {
		return nil, false
	}
	return o.Sources, true
}

// HasSources returns a boolean if a field has been set.
func (o *SearchResponse) HasSources() bool {
	if o != nil && !IsNil(o.Sources) {
		return true
	}

	return false
}

// SetSources gets a reference to the given string and assigns it to the Sources field.
func (o *SearchResponse) SetSources(v string) {
	o.Sources = &v
}

func (o SearchResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SearchResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Took) {
		toSerialize["took"] = o.Took
	}
	if !IsNil(o.TimedOut) {
		toSerialize["timed_out"] = o.TimedOut
	}
	if !IsNil(o.Aggregations) {
		toSerialize["aggregations"] = o.Aggregations
	}
	if !IsNil(o.Hits) {
		toSerialize["hits"] = o.Hits
	}
	if !IsNil(o.Profile) {
		toSerialize["profile"] = o.Profile
	}
	if !IsNil(o.Scroll) {
		toSerialize["scroll"] = o.Scroll
	}
	if !IsNil(o.Warning) {
		toSerialize["warning"] = o.Warning
	}
	if !IsNil(o.ConversationUuid) {
		toSerialize["conversation_uuid"] = o.ConversationUuid
	}
	if !IsNil(o.UserQuery) {
		toSerialize["user_query"] = o.UserQuery
	}
	if !IsNil(o.SearchQuery) {
		toSerialize["search_query"] = o.SearchQuery
	}
	if !IsNil(o.Response) {
		toSerialize["response"] = o.Response
	}
	if !IsNil(o.Sources) {
		toSerialize["sources"] = o.Sources
	}
	return toSerialize, nil
}

type NullableSearchResponse struct {
	value *SearchResponse
	isSet bool
}

func (v NullableSearchResponse) Get() *SearchResponse {
	return v.value
}

func (v *NullableSearchResponse) Set(val *SearchResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableSearchResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableSearchResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSearchResponse(val *SearchResponse) *NullableSearchResponse {
	return &NullableSearchResponse{value: val, isSet: true}
}

func (v NullableSearchResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSearchResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

