/*
Manticore Search Client

Сlient for Manticore Search. 

API version: 3.3.1
Contact: info@manticoresearch.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the AggregationComposite type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AggregationComposite{}

// AggregationComposite Composite aggregation
type AggregationComposite struct {
	// Maximum number of composite buckets in the result
	Size *int32 `json:"size,omitempty"`
	Sources []map[string]AggregationCompositeSourcesInnerValue `json:"sources,omitempty"`
}

// NewAggregationComposite instantiates a new AggregationComposite object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAggregationComposite() *AggregationComposite {
	this := AggregationComposite{}
	return &this
}

// NewAggregationCompositeWithDefaults instantiates a new AggregationComposite object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAggregationCompositeWithDefaults() *AggregationComposite {
	this := AggregationComposite{}
	return &this
}

// GetSize returns the Size field value if set, zero value otherwise.
func (o *AggregationComposite) GetSize() int32 {
	if o == nil || IsNil(o.Size) {
		var ret int32
		return ret
	}
	return *o.Size
}

// GetSizeOk returns a tuple with the Size field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AggregationComposite) GetSizeOk() (*int32, bool) {
	if o == nil || IsNil(o.Size) {
		return nil, false
	}
	return o.Size, true
}

// HasSize returns a boolean if a field has been set.
func (o *AggregationComposite) HasSize() bool {
	if o != nil && !IsNil(o.Size) {
		return true
	}

	return false
}

// SetSize gets a reference to the given int32 and assigns it to the Size field.
func (o *AggregationComposite) SetSize(v int32) {
	o.Size = &v
}

// GetSources returns the Sources field value if set, zero value otherwise.
func (o *AggregationComposite) GetSources() []map[string]AggregationCompositeSourcesInnerValue {
	if o == nil || IsNil(o.Sources) {
		var ret []map[string]AggregationCompositeSourcesInnerValue
		return ret
	}
	return o.Sources
}

// GetSourcesOk returns a tuple with the Sources field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AggregationComposite) GetSourcesOk() ([]map[string]AggregationCompositeSourcesInnerValue, bool) {
	if o == nil || IsNil(o.Sources) {
		return nil, false
	}
	return o.Sources, true
}

// HasSources returns a boolean if a field has been set.
func (o *AggregationComposite) HasSources() bool {
	if o != nil && !IsNil(o.Sources) {
		return true
	}

	return false
}

// SetSources gets a reference to the given []map[string]AggregationCompositeSourcesInnerValue and assigns it to the Sources field.
func (o *AggregationComposite) SetSources(v []map[string]AggregationCompositeSourcesInnerValue) {
	o.Sources = v
}

func (o AggregationComposite) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AggregationComposite) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Size) {
		toSerialize["size"] = o.Size
	}
	if !IsNil(o.Sources) {
		toSerialize["sources"] = o.Sources
	}
	return toSerialize, nil
}

type NullableAggregationComposite struct {
	value *AggregationComposite
	isSet bool
}

func (v NullableAggregationComposite) Get() *AggregationComposite {
	return v.value
}

func (v *NullableAggregationComposite) Set(val *AggregationComposite) {
	v.value = val
	v.isSet = true
}

func (v NullableAggregationComposite) IsSet() bool {
	return v.isSet
}

func (v *NullableAggregationComposite) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAggregationComposite(val *AggregationComposite) *NullableAggregationComposite {
	return &NullableAggregationComposite{value: val, isSet: true}
}

func (v NullableAggregationComposite) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAggregationComposite) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


