/*
Manticore Search Client

Сlient for Manticore Search. 

API version: 3.3.1
Contact: info@manticoresearch.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the FilterString type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FilterString{}

// FilterString Query filter
type FilterString struct {
	FilterField string `json:"filter_field"`
	Operation string `json:"operation"`
	FilterValue string `json:"filter_value"`
}

type _FilterString FilterString

// NewFilterString instantiates a new FilterString object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFilterString(filterField string, operation string, filterValue string) *FilterString {
	this := FilterString{}
	this.FilterField = filterField
	this.Operation = operation
	this.FilterValue = filterValue
	return &this
}

// NewFilterStringWithDefaults instantiates a new FilterString object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFilterStringWithDefaults() *FilterString {
	this := FilterString{}
	return &this
}

// GetFilterField returns the FilterField field value
func (o *FilterString) GetFilterField() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FilterField
}

// GetFilterFieldOk returns a tuple with the FilterField field value
// and a boolean to check if the value has been set.
func (o *FilterString) GetFilterFieldOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FilterField, true
}

// SetFilterField sets field value
func (o *FilterString) SetFilterField(v string) {
	o.FilterField = v
}

// GetOperation returns the Operation field value
func (o *FilterString) GetOperation() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Operation
}

// GetOperationOk returns a tuple with the Operation field value
// and a boolean to check if the value has been set.
func (o *FilterString) GetOperationOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Operation, true
}

// SetOperation sets field value
func (o *FilterString) SetOperation(v string) {
	o.Operation = v
}

// GetFilterValue returns the FilterValue field value
func (o *FilterString) GetFilterValue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FilterValue
}

// GetFilterValueOk returns a tuple with the FilterValue field value
// and a boolean to check if the value has been set.
func (o *FilterString) GetFilterValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FilterValue, true
}

// SetFilterValue sets field value
func (o *FilterString) SetFilterValue(v string) {
	o.FilterValue = v
}

func (o FilterString) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FilterString) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["filter_field"] = o.FilterField
	toSerialize["operation"] = o.Operation
	toSerialize["filter_value"] = o.FilterValue
	return toSerialize, nil
}

func (o *FilterString) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"filter_field",
		"operation",
		"filter_value",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFilterString := _FilterString{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varFilterString)

	if err != nil {
		return err
	}

	*o = FilterString(varFilterString)

	return err
}

type NullableFilterString struct {
	value *FilterString
	isSet bool
}

func (v NullableFilterString) Get() *FilterString {
	return v.value
}

func (v *NullableFilterString) Set(val *FilterString) {
	v.value = val
	v.isSet = true
}

func (v NullableFilterString) IsSet() bool {
	return v.isSet
}

func (v *NullableFilterString) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFilterString(val *FilterString) *NullableFilterString {
	return &NullableFilterString{value: val, isSet: true}
}

func (v NullableFilterString) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFilterString) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


