/*
Manticore Search Client

Сlient for Manticore Search. 

API version: 5.0.0
Contact: info@manticoresearch.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AggMetric type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AggMetric{}

// AggMetric Metric aggregation over a numeric field
type AggMetric struct {
	// Numeric field to aggregate
	Field string `json:"field"`
}

type _AggMetric AggMetric

// NewAggMetric instantiates a new AggMetric object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAggMetric(field string) *AggMetric {
	this := AggMetric{}
	this.Field = field
	return &this
}

// NewAggMetricWithDefaults instantiates a new AggMetric object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAggMetricWithDefaults() *AggMetric {
	this := AggMetric{}
	return &this
}

// GetField returns the Field field value
func (o *AggMetric) GetField() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Field
}

// GetFieldOk returns a tuple with the Field field value
// and a boolean to check if the value has been set.
func (o *AggMetric) GetFieldOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Field, true
}

// SetField sets field value
func (o *AggMetric) SetField(v string) {
	o.Field = v
}

func (o AggMetric) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AggMetric) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["field"] = o.Field
	return toSerialize, nil
}

func (o *AggMetric) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"field",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAggMetric := _AggMetric{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAggMetric)

	if err != nil {
		return err
	}

	*o = AggMetric(varAggMetric)

	return err
}

type NullableAggMetric struct {
	value *AggMetric
	isSet bool
}

func (v NullableAggMetric) Get() *AggMetric {
	return v.value
}

func (v *NullableAggMetric) Set(val *AggMetric) {
	v.value = val
	v.isSet = true
}

func (v NullableAggMetric) IsSet() bool {
	return v.isSet
}

func (v *NullableAggMetric) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAggMetric(val *AggMetric) *NullableAggMetric {
	return &NullableAggMetric{value: val, isSet: true}
}

func (v NullableAggMetric) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAggMetric) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

