/*
Manticore Search Client

Сlient for Manticore Search. 

API version: 3.3.1
Contact: info@manticoresearch.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GeoDistanceFilterLocationAnchor type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GeoDistanceFilterLocationAnchor{}

// GeoDistanceFilterLocationAnchor Geo pin point object
type GeoDistanceFilterLocationAnchor struct {
	// Geo latitude of pin point in degrees
	Lat *float32 `json:"lat,omitempty"`
	// Geo longitude pf pin point in degrees
	Lon *float32 `json:"lon,omitempty"`
}

// NewGeoDistanceFilterLocationAnchor instantiates a new GeoDistanceFilterLocationAnchor object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGeoDistanceFilterLocationAnchor() *GeoDistanceFilterLocationAnchor {
	this := GeoDistanceFilterLocationAnchor{}
	return &this
}

// NewGeoDistanceFilterLocationAnchorWithDefaults instantiates a new GeoDistanceFilterLocationAnchor object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGeoDistanceFilterLocationAnchorWithDefaults() *GeoDistanceFilterLocationAnchor {
	this := GeoDistanceFilterLocationAnchor{}
	return &this
}

// GetLat returns the Lat field value if set, zero value otherwise.
func (o *GeoDistanceFilterLocationAnchor) GetLat() float32 {
	if o == nil || IsNil(o.Lat) {
		var ret float32
		return ret
	}
	return *o.Lat
}

// GetLatOk returns a tuple with the Lat field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GeoDistanceFilterLocationAnchor) GetLatOk() (*float32, bool) {
	if o == nil || IsNil(o.Lat) {
		return nil, false
	}
	return o.Lat, true
}

// HasLat returns a boolean if a field has been set.
func (o *GeoDistanceFilterLocationAnchor) HasLat() bool {
	if o != nil && !IsNil(o.Lat) {
		return true
	}

	return false
}

// SetLat gets a reference to the given float32 and assigns it to the Lat field.
func (o *GeoDistanceFilterLocationAnchor) SetLat(v float32) {
	o.Lat = &v
}

// GetLon returns the Lon field value if set, zero value otherwise.
func (o *GeoDistanceFilterLocationAnchor) GetLon() float32 {
	if o == nil || IsNil(o.Lon) {
		var ret float32
		return ret
	}
	return *o.Lon
}

// GetLonOk returns a tuple with the Lon field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GeoDistanceFilterLocationAnchor) GetLonOk() (*float32, bool) {
	if o == nil || IsNil(o.Lon) {
		return nil, false
	}
	return o.Lon, true
}

// HasLon returns a boolean if a field has been set.
func (o *GeoDistanceFilterLocationAnchor) HasLon() bool {
	if o != nil && !IsNil(o.Lon) {
		return true
	}

	return false
}

// SetLon gets a reference to the given float32 and assigns it to the Lon field.
func (o *GeoDistanceFilterLocationAnchor) SetLon(v float32) {
	o.Lon = &v
}

func (o GeoDistanceFilterLocationAnchor) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GeoDistanceFilterLocationAnchor) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Lat) {
		toSerialize["lat"] = o.Lat
	}
	if !IsNil(o.Lon) {
		toSerialize["lon"] = o.Lon
	}
	return toSerialize, nil
}

type NullableGeoDistanceFilterLocationAnchor struct {
	value *GeoDistanceFilterLocationAnchor
	isSet bool
}

func (v NullableGeoDistanceFilterLocationAnchor) Get() *GeoDistanceFilterLocationAnchor {
	return v.value
}

func (v *NullableGeoDistanceFilterLocationAnchor) Set(val *GeoDistanceFilterLocationAnchor) {
	v.value = val
	v.isSet = true
}

func (v NullableGeoDistanceFilterLocationAnchor) IsSet() bool {
	return v.isSet
}

func (v *NullableGeoDistanceFilterLocationAnchor) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGeoDistanceFilterLocationAnchor(val *GeoDistanceFilterLocationAnchor) *NullableGeoDistanceFilterLocationAnchor {
	return &NullableGeoDistanceFilterLocationAnchor{value: val, isSet: true}
}

func (v NullableGeoDistanceFilterLocationAnchor) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGeoDistanceFilterLocationAnchor) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


