/*
Manticore Search Client

Сlient for Manticore Search. 

API version: 5.0.0
Contact: info@manticoresearch.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// FacetFilterMode Controls how facets inherit attribute filters from the main query. [Faceted search](https://manual.manticoresearch.com/Searching/Faceted_search#HTTP-JSON) 
type FacetFilterMode string

// List of facetFilterMode
const (
	STRICT FacetFilterMode = "strict"
	AUTO FacetFilterMode = "auto"
	MAX FacetFilterMode = "max"
)

// All allowed values of FacetFilterMode enum
var AllowedFacetFilterModeEnumValues = []FacetFilterMode{
	"strict",
	"auto",
	"max",
}

func (v *FacetFilterMode) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := FacetFilterMode(value)
	for _, existing := range AllowedFacetFilterModeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid FacetFilterMode", value)
}

// NewFacetFilterModeFromValue returns a pointer to a valid FacetFilterMode
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewFacetFilterModeFromValue(v string) (*FacetFilterMode, error) {
	ev := FacetFilterMode(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for FacetFilterMode: valid values are %v", v, AllowedFacetFilterModeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v FacetFilterMode) IsValid() bool {
	for _, existing := range AllowedFacetFilterModeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to facetFilterMode value
func (v FacetFilterMode) Ptr() *FacetFilterMode {
	return &v
}

type NullableFacetFilterMode struct {
	value *FacetFilterMode
	isSet bool
}

func (v NullableFacetFilterMode) Get() *FacetFilterMode {
	return v.value
}

func (v *NullableFacetFilterMode) Set(val *FacetFilterMode) {
	v.value = val
	v.isSet = true
}

func (v NullableFacetFilterMode) IsSet() bool {
	return v.isSet
}

func (v *NullableFacetFilterMode) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFacetFilterMode(val *FacetFilterMode) *NullableFacetFilterMode {
	return &NullableFacetFilterMode{value: val, isSet: true}
}

func (v NullableFacetFilterMode) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFacetFilterMode) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
