/*
Manticore Search Client

Сlient for Manticore Search. 

API version: 5.0.0
Contact: info@manticoresearch.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	_"bytes"
	_"fmt"
)

// checks if the UpdateDocumentRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateDocumentRequest{}

// UpdateDocumentRequest Payload for updating a document or multiple documents in a table
type UpdateDocumentRequest struct {
	// Name of the document table
	Table interface{} `json:"table"` 
	// Name of the document cluster
	Cluster interface{} `json:"cluster"` 
	// Object containing the document fields to update
	Doc interface{} `json:"doc"` 
	// Document ID
	Id interface{} `json:"id"` 
	Query *UpdateDocumentRequestQuery `json:"query"` 
}

type _UpdateDocumentRequest UpdateDocumentRequest

// NewUpdateDocumentRequest instantiates a new UpdateDocumentRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateDocumentRequest(table interface{}, doc interface{}) *UpdateDocumentRequest {
	this := UpdateDocumentRequest{}
	this.Table = table
	this.Doc = doc
	return &this
}

// NewUpdateDocumentRequestWithDefaults instantiates a new UpdateDocumentRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateDocumentRequestWithDefaults() *UpdateDocumentRequest {
	this := UpdateDocumentRequest{}
	return &this
}

// GetTable returns the Table field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *UpdateDocumentRequest) GetTable() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Table
}

// GetTableOk returns a tuple with the Table field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateDocumentRequest) GetTableOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Table) {
		return nil, false
	}
	return &o.Table, true
}

// SetTable sets field value
func (o *UpdateDocumentRequest) SetTable(v interface{}) {
	o.Table = v
}

// GetCluster returns the Cluster field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateDocumentRequest) GetCluster() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Cluster
}

// GetClusterOk returns a tuple with the Cluster field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateDocumentRequest) GetClusterOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Cluster) {
		return nil, false
	}
	return &o.Cluster, true
}

// HasCluster returns a boolean if a field has been set.
func (o *UpdateDocumentRequest) HasCluster() bool {
	if o != nil && !IsNil(o.Cluster) {
		return true
	}

	return false
}

// SetCluster gets a reference to the given interface{} and assigns it to the Cluster field.
func (o *UpdateDocumentRequest) SetCluster(v interface{}) {
	o.Cluster = v
}

// GetDoc returns the Doc field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *UpdateDocumentRequest) GetDoc() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Doc
}

// GetDocOk returns a tuple with the Doc field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateDocumentRequest) GetDocOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Doc) {
		return nil, false
	}
	return &o.Doc, true
}

// SetDoc sets field value
func (o *UpdateDocumentRequest) SetDoc(v interface{}) {
	o.Doc = v
}

// GetId returns the Id field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateDocumentRequest) GetId() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateDocumentRequest) GetIdOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return &o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *UpdateDocumentRequest) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given interface{} and assigns it to the Id field.
func (o *UpdateDocumentRequest) SetId(v interface{}) {
	o.Id = v
}

// GetQuery returns the Query field value if set, zero value otherwise.
func (o *UpdateDocumentRequest) GetQuery() UpdateDocumentRequestQuery {
	if o == nil || IsNil(o.Query) {
		var ret UpdateDocumentRequestQuery
		return ret
	}
	return *o.Query
}

// GetQueryOk returns a tuple with the Query field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateDocumentRequest) GetQueryOk() (*UpdateDocumentRequestQuery, bool) {
	if o == nil || IsNil(o.Query) {
		return nil, false
	}
	return o.Query, true
}

// HasQuery returns a boolean if a field has been set.
func (o *UpdateDocumentRequest) HasQuery() bool {
	if o != nil && !IsNil(o.Query) {
		return true
	}

	return false
}

// SetQuery gets a reference to the given UpdateDocumentRequestQuery and assigns it to the Query field.
func (o *UpdateDocumentRequest) SetQuery(v UpdateDocumentRequestQuery) {
	o.Query = &v
}

func (o UpdateDocumentRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateDocumentRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Table != nil {
		toSerialize["table"] = o.Table
	}
	if o.Cluster != nil {
		toSerialize["cluster"] = o.Cluster
	}
	if o.Doc != nil {
		toSerialize["doc"] = o.Doc
	}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Query) {
		toSerialize["query"] = o.Query
	}
	return toSerialize, nil
}

type NullableUpdateDocumentRequest struct {
	value *UpdateDocumentRequest
	isSet bool
}

func (v NullableUpdateDocumentRequest) Get() *UpdateDocumentRequest {
	return v.value
}

func (v *NullableUpdateDocumentRequest) Set(val *UpdateDocumentRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateDocumentRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateDocumentRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateDocumentRequest(val *UpdateDocumentRequest) *NullableUpdateDocumentRequest {
	return &NullableUpdateDocumentRequest{value: val, isSet: true}
}

func (v NullableUpdateDocumentRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateDocumentRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


