/*
Manticore Search Client

Сlient for Manticore Search. 

API version: 5.0.0
Contact: info@manticoresearch.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	_"fmt"
)

// HighlightAllOfHighlightQuery - Optional query object to customize highlighting behavior
type HighlightAllOfHighlightQuery struct {
	QueryFilter *QueryFilter
	Interface{} *interface{}
}

// QueryFilterAsHighlightAllOfHighlightQuery is a convenience function that returns QueryFilter wrapped in HighlightAllOfHighlightQuery
func QueryFilterAsHighlightAllOfHighlightQuery(v *QueryFilter) HighlightAllOfHighlightQuery {
	return HighlightAllOfHighlightQuery{
		QueryFilter: v,
	}
}

// interface{}AsHighlightAllOfHighlightQuery is a convenience function that returns interface{} wrapped in HighlightAllOfHighlightQuery
func Interface{}AsHighlightAllOfHighlightQuery(v *interface{}) HighlightAllOfHighlightQuery {
	return HighlightAllOfHighlightQuery{
		Interface{}: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *HighlightAllOfHighlightQuery) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into QueryFilter
	err = newStrictDecoder(data).Decode(&dst.QueryFilter)
	if err == nil {
		jsonQueryFilter, _ := json.Marshal(dst.QueryFilter)
		if string(jsonQueryFilter) == "{}" { // empty struct
			dst.QueryFilter = nil
		} else {
			if err = validator.Validate(dst.QueryFilter); err != nil {
				dst.QueryFilter = nil
			} else {
				match++
			}
		}
	} else {
		dst.QueryFilter = nil
	}

	// try to unmarshal data into Interface{}
	err = newStrictDecoder(data).Decode(&dst.Interface{})
	if err == nil {
		jsonInterface{}, _ := json.Marshal(dst.Interface{})
		if string(jsonInterface{}) == "{}" { // empty struct
			dst.Interface{} = nil
		} else {
			if err = validator.Validate(dst.Interface{}); err != nil {
				dst.Interface{} = nil
			} else {
				match++
			}
		}
	} else {
		dst.Interface{} = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.QueryFilter = nil
		dst.Interface{} = nil

		return fmt.Errorf("data matches more than one schema in oneOf(HighlightAllOfHighlightQuery)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(HighlightAllOfHighlightQuery)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src HighlightAllOfHighlightQuery) MarshalJSON() ([]byte, error) {
	if src.QueryFilter != nil {
		return json.Marshal(&src.QueryFilter)
	}

	if src.Interface{} != nil {
		return json.Marshal(&src.Interface{})
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *HighlightAllOfHighlightQuery) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.QueryFilter != nil {
		return obj.QueryFilter
	}

	if obj.Interface{} != nil {
		return obj.Interface{}
	}

	// all schemas are nil
	return nil
}

type NullableHighlightAllOfHighlightQuery struct {
	value *HighlightAllOfHighlightQuery
	isSet bool
}

func (v NullableHighlightAllOfHighlightQuery) Get() *HighlightAllOfHighlightQuery {
	return v.value
}

func (v *NullableHighlightAllOfHighlightQuery) Set(val *HighlightAllOfHighlightQuery) {
	v.value = val
	v.isSet = true
}

func (v NullableHighlightAllOfHighlightQuery) IsSet() bool {
	return v.isSet
}

func (v *NullableHighlightAllOfHighlightQuery) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHighlightAllOfHighlightQuery(val *HighlightAllOfHighlightQuery) *NullableHighlightAllOfHighlightQuery {
	return &NullableHighlightAllOfHighlightQuery{value: val, isSet: true}
}

func (v NullableHighlightAllOfHighlightQuery) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHighlightAllOfHighlightQuery) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


