/*
Manticore Search Client

Сlient for Manticore Search. 

API version: 3.3.1
Contact: info@manticoresearch.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the FilterNumber type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FilterNumber{}

// FilterNumber Query filter
type FilterNumber struct {
	FilterField string `json:"filter_field"`
	Operation string `json:"operation"`
	FilterValue float32 `json:"filter_value"`
}

type _FilterNumber FilterNumber

// NewFilterNumber instantiates a new FilterNumber object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFilterNumber(filterField string, operation string, filterValue float32) *FilterNumber {
	this := FilterNumber{}
	this.FilterField = filterField
	this.Operation = operation
	this.FilterValue = filterValue
	return &this
}

// NewFilterNumberWithDefaults instantiates a new FilterNumber object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFilterNumberWithDefaults() *FilterNumber {
	this := FilterNumber{}
	return &this
}

// GetFilterField returns the FilterField field value
func (o *FilterNumber) GetFilterField() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FilterField
}

// GetFilterFieldOk returns a tuple with the FilterField field value
// and a boolean to check if the value has been set.
func (o *FilterNumber) GetFilterFieldOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FilterField, true
}

// SetFilterField sets field value
func (o *FilterNumber) SetFilterField(v string) {
	o.FilterField = v
}

// GetOperation returns the Operation field value
func (o *FilterNumber) GetOperation() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Operation
}

// GetOperationOk returns a tuple with the Operation field value
// and a boolean to check if the value has been set.
func (o *FilterNumber) GetOperationOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Operation, true
}

// SetOperation sets field value
func (o *FilterNumber) SetOperation(v string) {
	o.Operation = v
}

// GetFilterValue returns the FilterValue field value
func (o *FilterNumber) GetFilterValue() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.FilterValue
}

// GetFilterValueOk returns a tuple with the FilterValue field value
// and a boolean to check if the value has been set.
func (o *FilterNumber) GetFilterValueOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FilterValue, true
}

// SetFilterValue sets field value
func (o *FilterNumber) SetFilterValue(v float32) {
	o.FilterValue = v
}

func (o FilterNumber) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FilterNumber) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["filter_field"] = o.FilterField
	toSerialize["operation"] = o.Operation
	toSerialize["filter_value"] = o.FilterValue
	return toSerialize, nil
}

func (o *FilterNumber) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"filter_field",
		"operation",
		"filter_value",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFilterNumber := _FilterNumber{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varFilterNumber)

	if err != nil {
		return err
	}

	*o = FilterNumber(varFilterNumber)

	return err
}

type NullableFilterNumber struct {
	value *FilterNumber
	isSet bool
}

func (v NullableFilterNumber) Get() *FilterNumber {
	return v.value
}

func (v *NullableFilterNumber) Set(val *FilterNumber) {
	v.value = val
	v.isSet = true
}

func (v NullableFilterNumber) IsSet() bool {
	return v.isSet
}

func (v *NullableFilterNumber) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFilterNumber(val *FilterNumber) *NullableFilterNumber {
	return &NullableFilterNumber{value: val, isSet: true}
}

func (v NullableFilterNumber) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFilterNumber) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


