/*
Manticore Search Client

Сlient for Manticore Search. 

API version: 5.0.0
Contact: info@manticoresearch.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	_"bytes"
	_"fmt"
)

// checks if the Match type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Match{}

// Match Filter helper object defining a match keyword and match options
type Match struct {
	Query string `json:"query"` 
	Operator interface{} `json:"operator"` 
	Boost interface{} `json:"boost"` 
}

type _Match Match

// NewMatch instantiates a new Match object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMatch(query string) *Match {
	this := Match{}
	this.Query = query
	return &this
}

// NewMatchWithDefaults instantiates a new Match object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMatchWithDefaults() *Match {
	this := Match{}
	return &this
}

// GetQuery returns the Query field value
func (o *Match) GetQuery() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Query
}

// GetQueryOk returns a tuple with the Query field value
// and a boolean to check if the value has been set.
func (o *Match) GetQueryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Query, true
}

// SetQuery sets field value
func (o *Match) SetQuery(v string) {
	o.Query = v
}

// GetOperator returns the Operator field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Match) GetOperator() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Operator
}

// GetOperatorOk returns a tuple with the Operator field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Match) GetOperatorOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Operator) {
		return nil, false
	}
	return &o.Operator, true
}

// HasOperator returns a boolean if a field has been set.
func (o *Match) HasOperator() bool {
	if o != nil && !IsNil(o.Operator) {
		return true
	}

	return false
}

// SetOperator gets a reference to the given interface{} and assigns it to the Operator field.
func (o *Match) SetOperator(v interface{}) {
	o.Operator = v
}

// GetBoost returns the Boost field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Match) GetBoost() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Boost
}

// GetBoostOk returns a tuple with the Boost field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Match) GetBoostOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Boost) {
		return nil, false
	}
	return &o.Boost, true
}

// HasBoost returns a boolean if a field has been set.
func (o *Match) HasBoost() bool {
	if o != nil && !IsNil(o.Boost) {
		return true
	}

	return false
}

// SetBoost gets a reference to the given interface{} and assigns it to the Boost field.
func (o *Match) SetBoost(v interface{}) {
	o.Boost = v
}

func (o Match) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Match) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["query"] = o.Query
	if o.Operator != nil {
		toSerialize["operator"] = o.Operator
	}
	if o.Boost != nil {
		toSerialize["boost"] = o.Boost
	}
	return toSerialize, nil
}

type NullableMatch struct {
	value *Match
	isSet bool
}

func (v NullableMatch) Get() *Match {
	return v.value
}

func (v *NullableMatch) Set(val *Match) {
	v.value = val
	v.isSet = true
}

func (v NullableMatch) IsSet() bool {
	return v.isSet
}

func (v *NullableMatch) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMatch(val *Match) *NullableMatch {
	return &NullableMatch{value: val, isSet: true}
}

func (v NullableMatch) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMatch) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


