/*
Manticore Search Client

Сlient for Manticore Search. 

API version: 5.0.0
Contact: info@manticoresearch.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Knn type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Knn{}

// Knn Object representing a k-nearest neighbor search query
type Knn struct {
	// Field to perform the k-nearest neighbor search on
	Field string `json:"field"`
	// The number of nearest neighbors to return
	K int32 `json:"k"`
	Query *KnnQuery `json:"query,omitempty"`
	// The vector used as input for the KNN search
	QueryVector []float32 `json:"query_vector,omitempty"`
	// The docuemnt ID used as input for the KNN search
	DocId *uint64 `json:"doc_id,omitempty"`
	// Optional parameter controlling the accuracy of the search
	Ef *int32 `json:"ef,omitempty"`
	Filter *QueryFilter `json:"filter,omitempty"`
}

type _Knn Knn

// NewKnn instantiates a new Knn object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKnn(field string, k int32) *Knn {
	this := Knn{}
	this.Field = field
	this.K = k
	return &this
}

// NewKnnWithDefaults instantiates a new Knn object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKnnWithDefaults() *Knn {
	this := Knn{}
	return &this
}

// GetField returns the Field field value
func (o *Knn) GetField() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Field
}

// GetFieldOk returns a tuple with the Field field value
// and a boolean to check if the value has been set.
func (o *Knn) GetFieldOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Field, true
}

// SetField sets field value
func (o *Knn) SetField(v string) {
	o.Field = v
}

// GetK returns the K field value
func (o *Knn) GetK() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.K
}

// GetKOk returns a tuple with the K field value
// and a boolean to check if the value has been set.
func (o *Knn) GetKOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.K, true
}

// SetK sets field value
func (o *Knn) SetK(v int32) {
	o.K = v
}

// GetQuery returns the Query field value if set, zero value otherwise.
func (o *Knn) GetQuery() KnnQuery {
	if o == nil || IsNil(o.Query) {
		var ret KnnQuery
		return ret
	}
	return *o.Query
}

// GetQueryOk returns a tuple with the Query field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Knn) GetQueryOk() (*KnnQuery, bool) {
	if o == nil || IsNil(o.Query) {
		return nil, false
	}
	return o.Query, true
}

// HasQuery returns a boolean if a field has been set.
func (o *Knn) HasQuery() bool {
	if o != nil && !IsNil(o.Query) {
		return true
	}

	return false
}

// SetQuery gets a reference to the given KnnQuery and assigns it to the Query field.
func (o *Knn) SetQuery(v KnnQuery) {
	o.Query = &v
}

// GetQueryVector returns the QueryVector field value if set, zero value otherwise.
func (o *Knn) GetQueryVector() []float32 {
	if o == nil || IsNil(o.QueryVector) {
		var ret []float32
		return ret
	}
	return o.QueryVector
}

// GetQueryVectorOk returns a tuple with the QueryVector field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Knn) GetQueryVectorOk() ([]float32, bool) {
	if o == nil || IsNil(o.QueryVector) {
		return nil, false
	}
	return o.QueryVector, true
}

// HasQueryVector returns a boolean if a field has been set.
func (o *Knn) HasQueryVector() bool {
	if o != nil && !IsNil(o.QueryVector) {
		return true
	}

	return false
}

// SetQueryVector gets a reference to the given []float32 and assigns it to the QueryVector field.
func (o *Knn) SetQueryVector(v []float32) {
	o.QueryVector = v
}

// GetDocId returns the DocId field value if set, zero value otherwise.
func (o *Knn) GetDocId() uint64 {
	if o == nil || IsNil(o.DocId) {
		var ret uint64
		return ret
	}
	return *o.DocId
}

// GetDocIdOk returns a tuple with the DocId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Knn) GetDocIdOk() (*uint64, bool) {
	if o == nil || IsNil(o.DocId) {
		return nil, false
	}
	return o.DocId, true
}

// HasDocId returns a boolean if a field has been set.
func (o *Knn) HasDocId() bool {
	if o != nil && !IsNil(o.DocId) {
		return true
	}

	return false
}

// SetDocId gets a reference to the given uint64 and assigns it to the DocId field.
func (o *Knn) SetDocId(v uint64) {
	o.DocId = &v
}

// GetEf returns the Ef field value if set, zero value otherwise.
func (o *Knn) GetEf() int32 {
	if o == nil || IsNil(o.Ef) {
		var ret int32
		return ret
	}
	return *o.Ef
}

// GetEfOk returns a tuple with the Ef field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Knn) GetEfOk() (*int32, bool) {
	if o == nil || IsNil(o.Ef) {
		return nil, false
	}
	return o.Ef, true
}

// HasEf returns a boolean if a field has been set.
func (o *Knn) HasEf() bool {
	if o != nil && !IsNil(o.Ef) {
		return true
	}

	return false
}

// SetEf gets a reference to the given int32 and assigns it to the Ef field.
func (o *Knn) SetEf(v int32) {
	o.Ef = &v
}

// GetFilter returns the Filter field value if set, zero value otherwise.
func (o *Knn) GetFilter() QueryFilter {
	if o == nil || IsNil(o.Filter) {
		var ret QueryFilter
		return ret
	}
	return *o.Filter
}

// GetFilterOk returns a tuple with the Filter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Knn) GetFilterOk() (*QueryFilter, bool) {
	if o == nil || IsNil(o.Filter) {
		return nil, false
	}
	return o.Filter, true
}

// HasFilter returns a boolean if a field has been set.
func (o *Knn) HasFilter() bool {
	if o != nil && !IsNil(o.Filter) {
		return true
	}

	return false
}

// SetFilter gets a reference to the given QueryFilter and assigns it to the Filter field.
func (o *Knn) SetFilter(v QueryFilter) {
	o.Filter = &v
}

func (o Knn) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Knn) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["field"] = o.Field
	toSerialize["k"] = o.K
	if !IsNil(o.Query) {
		toSerialize["query"] = o.Query
	}
	if !IsNil(o.QueryVector) {
		toSerialize["query_vector"] = o.QueryVector
	}
	if !IsNil(o.DocId) {
		toSerialize["doc_id"] = o.DocId
	}
	if !IsNil(o.Ef) {
		toSerialize["ef"] = o.Ef
	}
	if !IsNil(o.Filter) {
		toSerialize["filter"] = o.Filter
	}
	return toSerialize, nil
}

func (o *Knn) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"field",
		"k",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varKnn := _Knn{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varKnn)

	if err != nil {
		return err
	}

	*o = Knn(varKnn)

	return err
}

type NullableKnn struct {
	value *Knn
	isSet bool
}

func (v NullableKnn) Get() *Knn {
	return v.value
}

func (v *NullableKnn) Set(val *Knn) {
	v.value = val
	v.isSet = true
}

func (v NullableKnn) IsSet() bool {
	return v.isSet
}

func (v *NullableKnn) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKnn(val *Knn) *NullableKnn {
	return &NullableKnn{value: val, isSet: true}
}

func (v NullableKnn) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKnn) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

