/*
Manticore Search Client

Сlient for Manticore Search. 

API version: 5.0.0
Contact: info@manticoresearch.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AggHistogram type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AggHistogram{}

// AggHistogram Object to use histograms in aggregation, i.e., grouping search results by histogram values
type AggHistogram struct {
	// Field to group by
	Field string `json:"field"`
	// Interval of the histogram values
	Interval int32 `json:"interval"`
	// Offset of the histogram values. Default value is 0.
	Offset *int32 `json:"offset,omitempty"`
	// Flag that defines if a search response will be a dictionary with the bucket keys. Default value is false.
	Keyed *bool `json:"keyed,omitempty"`
}

type _AggHistogram AggHistogram

// NewAggHistogram instantiates a new AggHistogram object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAggHistogram(field string, interval int32) *AggHistogram {
	this := AggHistogram{}
	this.Field = field
	this.Interval = interval
	return &this
}

// NewAggHistogramWithDefaults instantiates a new AggHistogram object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAggHistogramWithDefaults() *AggHistogram {
	this := AggHistogram{}
	return &this
}

// GetField returns the Field field value
func (o *AggHistogram) GetField() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Field
}

// GetFieldOk returns a tuple with the Field field value
// and a boolean to check if the value has been set.
func (o *AggHistogram) GetFieldOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Field, true
}

// SetField sets field value
func (o *AggHistogram) SetField(v string) {
	o.Field = v
}

// GetInterval returns the Interval field value
func (o *AggHistogram) GetInterval() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Interval
}

// GetIntervalOk returns a tuple with the Interval field value
// and a boolean to check if the value has been set.
func (o *AggHistogram) GetIntervalOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Interval, true
}

// SetInterval sets field value
func (o *AggHistogram) SetInterval(v int32) {
	o.Interval = v
}

// GetOffset returns the Offset field value if set, zero value otherwise.
func (o *AggHistogram) GetOffset() int32 {
	if o == nil || IsNil(o.Offset) {
		var ret int32
		return ret
	}
	return *o.Offset
}

// GetOffsetOk returns a tuple with the Offset field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AggHistogram) GetOffsetOk() (*int32, bool) {
	if o == nil || IsNil(o.Offset) {
		return nil, false
	}
	return o.Offset, true
}

// HasOffset returns a boolean if a field has been set.
func (o *AggHistogram) HasOffset() bool {
	if o != nil && !IsNil(o.Offset) {
		return true
	}

	return false
}

// SetOffset gets a reference to the given int32 and assigns it to the Offset field.
func (o *AggHistogram) SetOffset(v int32) {
	o.Offset = &v
}

// GetKeyed returns the Keyed field value if set, zero value otherwise.
func (o *AggHistogram) GetKeyed() bool {
	if o == nil || IsNil(o.Keyed) {
		var ret bool
		return ret
	}
	return *o.Keyed
}

// GetKeyedOk returns a tuple with the Keyed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AggHistogram) GetKeyedOk() (*bool, bool) {
	if o == nil || IsNil(o.Keyed) {
		return nil, false
	}
	return o.Keyed, true
}

// HasKeyed returns a boolean if a field has been set.
func (o *AggHistogram) HasKeyed() bool {
	if o != nil && !IsNil(o.Keyed) {
		return true
	}

	return false
}

// SetKeyed gets a reference to the given bool and assigns it to the Keyed field.
func (o *AggHistogram) SetKeyed(v bool) {
	o.Keyed = &v
}

func (o AggHistogram) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AggHistogram) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["field"] = o.Field
	toSerialize["interval"] = o.Interval
	if !IsNil(o.Offset) {
		toSerialize["offset"] = o.Offset
	}
	if !IsNil(o.Keyed) {
		toSerialize["keyed"] = o.Keyed
	}
	return toSerialize, nil
}

func (o *AggHistogram) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"field",
		"interval",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAggHistogram := _AggHistogram{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAggHistogram)

	if err != nil {
		return err
	}

	*o = AggHistogram(varAggHistogram)

	return err
}

type NullableAggHistogram struct {
	value *AggHistogram
	isSet bool
}

func (v NullableAggHistogram) Get() *AggHistogram {
	return v.value
}

func (v *NullableAggHistogram) Set(val *AggHistogram) {
	v.value = val
	v.isSet = true
}

func (v NullableAggHistogram) IsSet() bool {
	return v.isSet
}

func (v *NullableAggHistogram) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAggHistogram(val *AggHistogram) *NullableAggHistogram {
	return &NullableAggHistogram{value: val, isSet: true}
}

func (v NullableAggHistogram) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAggHistogram) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


