/*
Manticore Search Client

Сlient for Manticore Search. 

API version: 5.0.0
Contact: info@manticoresearch.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"gopkg.in/validator.v2"
	"fmt"
)

// ErrorResponseError - struct for ErrorResponseError
type ErrorResponseError struct {
	ErrorResponseErrorOneOf *ErrorResponseErrorOneOf
	String *string
}

// ErrorResponseErrorOneOfAsErrorResponseError is a convenience function that returns ErrorResponseErrorOneOf wrapped in ErrorResponseError
func ErrorResponseErrorOneOfAsErrorResponseError(v *ErrorResponseErrorOneOf) ErrorResponseError {
	return ErrorResponseError{
		ErrorResponseErrorOneOf: v,
	}
}

// stringAsErrorResponseError is a convenience function that returns string wrapped in ErrorResponseError
func StringAsErrorResponseError(v *string) ErrorResponseError {
	return ErrorResponseError{
		String: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *ErrorResponseError) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into ErrorResponseErrorOneOf
	err = newStrictDecoder(data).Decode(&dst.ErrorResponseErrorOneOf)
	if err == nil {
		jsonErrorResponseErrorOneOf, _ := json.Marshal(dst.ErrorResponseErrorOneOf)
		if string(jsonErrorResponseErrorOneOf) == "{}" { // empty struct
			dst.ErrorResponseErrorOneOf = nil
		} else {
			if err = validator.Validate(dst.ErrorResponseErrorOneOf); err != nil {
				dst.ErrorResponseErrorOneOf = nil
			} else {
				match++
			}
		}
	} else {
		dst.ErrorResponseErrorOneOf = nil
	}

	// try to unmarshal data into String
	err = newStrictDecoder(data).Decode(&dst.String)
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			if err = validator.Validate(dst.String); err != nil {
				dst.String = nil
			} else {
				match++
			}
		}
	} else {
		dst.String = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.ErrorResponseErrorOneOf = nil
		dst.String = nil

		return fmt.Errorf("data matches more than one schema in oneOf(ErrorResponseError)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(ErrorResponseError)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src ErrorResponseError) MarshalJSON() ([]byte, error) {
	if src.ErrorResponseErrorOneOf != nil {
		return json.Marshal(&src.ErrorResponseErrorOneOf)
	}

	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *ErrorResponseError) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.ErrorResponseErrorOneOf != nil {
		return obj.ErrorResponseErrorOneOf
	}

	if obj.String != nil {
		return obj.String
	}

	// all schemas are nil
	return nil
}

type NullableErrorResponseError struct {
	value *ErrorResponseError
	isSet bool
}

func (v NullableErrorResponseError) Get() *ErrorResponseError {
	return v.value
}

func (v *NullableErrorResponseError) Set(val *ErrorResponseError) {
	v.value = val
	v.isSet = true
}

func (v NullableErrorResponseError) IsSet() bool {
	return v.isSet
}

func (v *NullableErrorResponseError) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableErrorResponseError(val *ErrorResponseError) *NullableErrorResponseError {
	return &NullableErrorResponseError{value: val, isSet: true}
}

func (v NullableErrorResponseError) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableErrorResponseError) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


