name: Publishing

on: [push]

jobs:
  test:
    uses: ./.github/workflows/test.yml
  publish:
    name: Publish the client to the public registry
    needs: [test]
    runs-on: ubuntu-22.04
    env:
      VERSION: ${{ github.ref_name }}
    strategy:
      matrix:
        go: [ '17' ]

    steps:
    - uses: actions/checkout@v2
    - name: Setup Go ${{ matrix.go-version }}
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}
    - name: Install dependencies
      run: go get .    
    - name: Publish
      run: |
        go mod tidy
        GOPROXY=proxy.golang.org go list -m github.com/manticoresoftware/manticoresearch-go@v1.0.0

